# Strict state two letter codes plus DC & PR
# in json format


_STATE_CODES = {
    "AL": {"isoCode": "AL", "name": "Alabama", "abbr": "Ala."},
    "AK": {"isoCode": "AK", "name": "Alaska", "abbr": "Alaska"},
    "AZ": {"isoCode": "AZ", "name": "Arizona", "abbr": "Ariz."},
    "AR": {"isoCode": "AR", "name": "Arkansas", "abbr": "Ark."},
    "CA": {"isoCode": "CA", "name": "California", "abbr": "Calif."},
    "CO": {"isoCode": "CO", "name": "Colorado", "abbr": "Colo."},
    "CT": {"isoCode": "CT", "name": "Connecticut", "abbr": "Conn."},
    "DC": {"isoCode": "DC", "name": "District of Columbia", "abbr": "D.C."},
    "DE": {"isoCode": "DE", "name": "Delaware", "abbr": "Del."},
    "FL": {"isoCode": "FL", "name": "Florida", "abbr": "Fla."},
    "GA": {"isoCode": "GA", "name": "Georgia", "abbr": "Ga."},
    "HI": {"isoCode": "HI", "name": "Hawaii", "abbr": "Hawaii"},
    "ID": {"isoCode": "ID", "name": "Idaho", "abbr": "Idaho"},
    "IL": {"isoCode": "IL", "name": "Illinois", "abbr": "Ill."},
    "IN": {"isoCode": "IN", "name": "Indiana", "abbr": "Ind."},
    "IA": {"isoCode": "IA", "name": "Iowa", "abbr": "Iowa"},
    "KS": {"isoCode": "KS", "name": "Kansas", "abbr": "Kans."},
    "KY": {"isoCode": "KY", "name": "Kentucky", "abbr": "Ky."},
    "LA": {"isoCode": "LA", "name": "Louisiana", "abbr": "La."},
    "ME": {"isoCode": "ME", "name": "Maine", "abbr": "Maine"},
    "MD": {"isoCode": "MD", "name": "Maryland", "abbr": "Md."},
    "MA": {"isoCode": "MA", "name": "Massachusetts", "abbr": "Mass."},
    "MI": {"isoCode": "MI", "name": "Michigan", "abbr": "Mich."},
    "MN": {"isoCode": "MN", "name": "Minnesota", "abbr": "Minn."},
    "MS": {"isoCode": "MS", "name": "Mississippi", "abbr": "Miss."},
    "MO": {"isoCode": "MO", "name": "Missouri", "abbr": "Mo."},
    "MT": {"isoCode": "MT", "name": "Montana", "abbr": "Mont."},
    "NE": {"isoCode": "NE", "name": "Nebraska", "abbr": "Nebr."},
    "NV": {"isoCode": "NV", "name": "Nevada", "abbr": "Nev."},
    "NH": {"isoCode": "NH", "name": "New Hampshire", "abbr": "N.H."},
    "NJ": {"isoCode": "NJ", "name": "New Jersey", "abbr": "N.J."},
    "NM": {"isoCode": "NM", "name": "New Mexico", "abbr": "N.M."},
    "NY": {"isoCode": "NY", "name": "New York", "abbr": "N.Y."},
    "NC": {"isoCode": "NC", "name": "North Carolina", "abbr": "N.C."},
    "ND": {"isoCode": "ND", "name": "North Dakota", "abbr": "N.D."},
    "OH": {"isoCode": "OH", "name": "Ohio", "abbr": "Ohio"},
    "OK": {"isoCode": "OK", "name": "Oklahoma", "abbr": "Okla."},
    "OR": {"isoCode": "OR", "name": "Oregon", "abbr": "Ore."},
    "PA": {"isoCode": "PA", "name": "Pennsylvania", "abbr": "Pa."},
    "PR": {"isoCode": "PR", "name": "Puerto Rico", "abbr": "P.R."},
    "RI": {"isoCode": "RI", "name": "Rhode Island", "abbr": "R.I."},
    "SC": {"isoCode": "SC", "name": "South Carolina", "abbr": "S.C."},
    "SD": {"isoCode": "SD", "name": "South Dakota", "abbr": "S.D."},
    "TN": {"isoCode": "TN", "name": "Tennessee", "abbr": "Tenn."},
    "TX": {"isoCode": "TX", "name": "Texas", "abbr": "Tex."},
    "UT": {"isoCode": "UT", "name": "Utah", "abbr": "Utah"},
    "VT": {"isoCode": "VT", "name": "Vermont", "abbr": "Vt."},
    "VA": {"isoCode": "VA", "name": "Virginia", "abbr": "Va."},
    "WA": {"isoCode": "WA", "name": "Washington", "abbr": "Wash."},
    "WV": {"isoCode": "WV", "name": "West Virginia", "abbr": "W.Va."},
    "WI": {"isoCode": "WI", "name": "Wisconsin", "abbr": "Wis."},
    "WY": {"isoCode": "WY", "name": "Wyoming", "abbr": "Wyo."},
}
