"""empty message

Revision ID: 03828ce2c602
Revises: cf19ba0b998c
Create Date: 2026-03-30 07:24:23.092073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03828ce2c602'
down_revision = 'cf19ba0b998c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_cron_lock',
    sa.Column('lock_key', sa.String(length=255), nullable=False),
    sa.Column('job_key', sa.String(length=120), nullable=False),
    sa.Column('unit_key', sa.String(length=120), nullable=False),
    sa.Column('owner_run_ulid', sa.String(length=26), nullable=False),
    sa.Column('acquired_at_utc', sa.String(length=30), nullable=False),
    sa.Column('expires_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('lock_key')
    )
    with op.batch_alter_table('admin_cron_lock', schema=None) as batch_op:
        batch_op.create_index('ix_admin_cron_lock_job_unit', ['job_key', 'unit_key'], unique=False)

    op.create_table('admin_cron_run',
    sa.Column('job_key', sa.String(length=120), nullable=False),
    sa.Column('unit_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at_utc', sa.String(length=30), nullable=False),
    sa.Column('finished_at_utc', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('trigger_mode', sa.String(length=32), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('job_key', 'unit_key', 'attempt_no', name='uq_admin_cron_run_job_unit_attempt')
    )
    with op.batch_alter_table('admin_cron_run', schema=None) as batch_op:
        batch_op.create_index('ix_admin_cron_run_job_started', ['job_key', 'started_at_utc'], unique=False)
        batch_op.create_index('ix_admin_cron_run_status_started', ['status', 'started_at_utc'], unique=False)

    op.create_table('resource_admin_review_request',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('review_kind', sa.String(length=64), nullable=False),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('resource_admin_review_request', schema=None) as batch_op:
        batch_op.create_index('ix_resource_admin_review_request_active', ['entity_ulid', 'review_kind', 'source_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_admin_review_request', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_admin_review_request_active')

    op.drop_table('resource_admin_review_request')
    with op.batch_alter_table('admin_cron_run', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_cron_run_status_started')
        batch_op.drop_index('ix_admin_cron_run_job_started')

    op.drop_table('admin_cron_run')
    with op.batch_alter_table('admin_cron_lock', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_cron_lock_job_unit')

    op.drop_table('admin_cron_lock')
    # ### end Alembic commands ###
