"""empty message

Revision ID: 04e68a613ae9
Revises: e236a9cc0f97
Create Date: 2026-01-14 11:59:32.289806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e68a613ae9'
down_revision = 'e236a9cc0f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_poc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_poc_org_entity_ulid'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entity_entity', ['person_entity_ulid'], ['ulid'], ondelete='RESTRICT')
        batch_op.drop_column('org_entity_ulid')

    with op.batch_alter_table('sponsor_poc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_poc_org_entity_ulid'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entity_entity', ['person_entity_ulid'], ['ulid'], ondelete='RESTRICT')
        batch_op.drop_column('org_entity_ulid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_poc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_entity_ulid', sa.VARCHAR(length=26), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entity_person', ['person_entity_ulid'], ['ulid'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'entity_org', ['org_entity_ulid'], ['ulid'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_sponsor_poc_org_entity_ulid'), ['org_entity_ulid'], unique=False)

    with op.batch_alter_table('resource_poc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_entity_ulid', sa.VARCHAR(length=26), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'entity_person', ['person_entity_ulid'], ['ulid'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'entity_org', ['org_entity_ulid'], ['ulid'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_resource_poc_org_entity_ulid'), ['org_entity_ulid'], unique=False)

    # ### end Alembic commands ###
