"""initial schema (entity-centric)

Revision ID: 0735607b935c
Revises:
Create Date: 2025-09-25 18:52:22.111978

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0735607b935c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_entity",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "governance_authorization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_key", sa.String(length=120), nullable=False),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "policy_key",
            "role_name",
            "action",
            name="uq_authz_key_role_action",
        ),
    )
    op.create_table(
        "governance_office",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "governance_officer_term",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("primary_user_id", sa.Integer(), nullable=True),
        sa.Column("pro_tem_user_id", sa.Integer(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "governance_policy",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_roles_name"), ["name"], unique=True
        )

    op.create_table(
        "transactions_ledger",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column("slice", sa.String(length=48), nullable=False),
        sa.Column("operation", sa.String(length=48), nullable=True),
        sa.Column("happened_at_utc", sa.DateTime(), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=True),
        sa.Column("customer_id", sa.String(length=26), nullable=True),
        sa.Column("changed_fields_json", sa.Text(), nullable=True),
        sa.Column("entity_ids_json", sa.Text(), nullable=True),
        sa.Column("refs_json", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=26), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("prev_event_id", sa.String(length=26), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("transactions_ledger", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ledger_customer", ["customer_id"], unique=False
        )
        batch_op.create_index(
            "ix_ledger_hash", ["id", "event_hash"], unique=False
        )
        batch_op.create_index(
            "ix_ledger_slice_when", ["slice", "happened_at_utc"], unique=False
        )
        batch_op.create_index("ix_ledger_type", ["type"], unique=False)
        batch_op.create_index(
            "ix_ledger_when", ["happened_at_utc"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "entity_address",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("entity_id", sa.String(length=26), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("address1", sa.String(length=120), nullable=False),
        sa.Column("address2", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("postal", sa.String(length=12), nullable=False),
        sa.Column("tz", sa.String(length=40), nullable=True),
        sa.Column("is_primary", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "is_primary in (0,1)", name="ck_address_is_primary"
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity_entity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id",
            "purpose",
            "is_primary",
            name="ux_address_primary_by_purpose",
        ),
    )
    op.create_table(
        "entity_contact",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("entity_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("is_primary", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "is_primary in (0,1)", name="ck_contact_is_primary"
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity_entity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id",
            "kind",
            "is_primary",
            name="ux_contact_primary_per_kind",
        ),
    )
    op.create_table(
        "entity_org",
        sa.Column("entity_id", sa.String(length=26), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("doing_business_as", sa.String(length=200), nullable=True),
        sa.Column("ein", sa.String(length=9), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity_entity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    with op.batch_alter_table("entity_org", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_org_ein"), ["ein"], unique=False
        )

    op.create_table(
        "entity_person",
        sa.Column("entity_id", sa.String(length=26), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("preferred_name", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity_entity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "entity_role",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("entity_id", sa.String(length=26), nullable=False),
        sa.Column("role_code", sa.String(length=24), nullable=False),
        sa.Column("granted_at_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity_entity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "role_code", name="ux_entity_role"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("entity_role")
    op.drop_table("entity_person")
    with op.batch_alter_table("entity_org", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_org_ein"))

    op.drop_table("entity_org")
    op.drop_table("entity_contact")
    op.drop_table("entity_address")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("transactions_ledger", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_when")
        batch_op.drop_index("ix_ledger_type")
        batch_op.drop_index("ix_ledger_slice_when")
        batch_op.drop_index("ix_ledger_hash")
        batch_op.drop_index("ix_ledger_customer")

    op.drop_table("transactions_ledger")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))

    op.drop_table("roles")
    op.drop_table("governance_policy")
    op.drop_table("governance_officer_term")
    op.drop_table("governance_office")
    op.drop_table("governance_authorization")
    op.drop_table("entity_entity")
    # ### end Alembic commands ###
