"""empty message

Revision ID: 15c07f72ab70
Revises: 93aecaaa8f00
Create Date: 2026-04-23 09:02:32.647160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c07f72ab70'
down_revision = '93aecaaa8f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_admin_issue',
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('sponsor_admin_issue', schema=None) as batch_op:
        batch_op.create_index('ix_sponsor_admin_issue_active', ['reason_code', 'source_status', 'closed_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_admin_issue_closed_at_utc'), ['closed_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_admin_issue_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_admin_issue_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_sponsor_admin_issue_request_reason', ['request_id', 'reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_admin_issue_source_status'), ['source_status'], unique=False)
        batch_op.create_index('ix_sponsor_admin_issue_target_reason', ['target_ulid', 'reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_admin_issue_target_ulid'), ['target_ulid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_admin_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_admin_issue_target_ulid'))
        batch_op.drop_index('ix_sponsor_admin_issue_target_reason')
        batch_op.drop_index(batch_op.f('ix_sponsor_admin_issue_source_status'))
        batch_op.drop_index('ix_sponsor_admin_issue_request_reason')
        batch_op.drop_index(batch_op.f('ix_sponsor_admin_issue_request_id'))
        batch_op.drop_index(batch_op.f('ix_sponsor_admin_issue_reason_code'))
        batch_op.drop_index(batch_op.f('ix_sponsor_admin_issue_closed_at_utc'))
        batch_op.drop_index('ix_sponsor_admin_issue_active')

    op.drop_table('sponsor_admin_issue')
    # ### end Alembic commands ###
