"""empty message

Revision ID: 1bc4b0e02e6c
Revises: e83f1b1a7063
Create Date: 2026-04-25 09:59:14.774721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc4b0e02e6c'
down_revision = 'e83f1b1a7063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triaged_by_actor_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('triaged_at_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('snoozed_until_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_alert_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('triage_note', sa.Text(), nullable=True))

    with op.batch_alter_table('admin_alert_archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triaged_by_actor_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('triaged_at_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('snoozed_until_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_alert_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('triage_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_alert_archive', schema=None) as batch_op:
        batch_op.drop_column('triage_note')
        batch_op.drop_column('duplicate_of_alert_ulid')
        batch_op.drop_column('snoozed_until_utc')
        batch_op.drop_column('triaged_at_utc')
        batch_op.drop_column('triaged_by_actor_ulid')

    with op.batch_alter_table('admin_alert', schema=None) as batch_op:
        batch_op.drop_column('triage_note')
        batch_op.drop_column('duplicate_of_alert_ulid')
        batch_op.drop_column('snoozed_until_utc')
        batch_op.drop_column('triaged_at_utc')
        batch_op.drop_column('triaged_by_actor_ulid')

    # ### end Alembic commands ###
