"""add finance admin issue

Revision ID: 24ff0ac6c03e
Revises: db8d7df1ee81
Create Date: 2026-04-27 18:20:54.360070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ff0ac6c03e'
down_revision = 'db8d7df1ee81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_admin_issue',
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('issue_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=False),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detection_json', sa.JSON(), nullable=False),
    sa.Column('preview_json', sa.JSON(), nullable=False),
    sa.Column('resolution_json', sa.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('review_started_at_utc', sa.String(length=30), nullable=True),
    sa.Column('review_started_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('resolved_at_utc', sa.String(length=30), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('admin_alert_ulid', sa.String(length=26), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("issue_status in ('open','in_review','resolved','false_positive','manual_resolution_required')", name='ck_finance_admin_issue_status'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_admin_alert_ulid'), ['admin_alert_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_issue_status'), ['issue_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index('ix_finance_admin_issue_reason_status', ['reason_code', 'issue_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_finance_admin_issue_request_reason', ['request_id', 'reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_source_status'), ['source_status'], unique=False)
        batch_op.create_index('ix_finance_admin_issue_status_updated', ['issue_status', 'updated_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_target_ulid'), ['target_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_workflow_key'), ['workflow_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_workflow_key'))
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_target_ulid'))
        batch_op.drop_index('ix_finance_admin_issue_status_updated')
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_source_status'))
        batch_op.drop_index('ix_finance_admin_issue_request_reason')
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_request_id'))
        batch_op.drop_index('ix_finance_admin_issue_reason_status')
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_reason_code'))
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_issue_status'))
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_admin_alert_ulid'))

    op.drop_table('finance_admin_issue')
    # ### end Alembic commands ###
