"""empty message

Revision ID: 262009fc4ee7
Revises: 063a5140884e
Create Date: 2026-03-02 21:41:29.190492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262009fc4ee7'
down_revision = '063a5140884e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_cron_status',
    sa.Column('job_name', sa.String(length=120), nullable=False),
    sa.Column('last_success_utc', sa.String(length=30), nullable=True),
    sa.Column('last_error_utc', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('finance_account',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("type in ('asset','liability','net_assets','revenue','expense')", name='ck_account_type'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_account_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_account_type'), ['type'], unique=False)

    op.create_table('finance_balance_monthly',
    sa.Column('account_code', sa.String(length=24), nullable=False),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('debits_cents', sa.Integer(), nullable=False),
    sa.Column('credits_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('account_code', 'fund_code', 'project_ulid', 'period_key', name='uq_balance_key')
    )
    with op.batch_alter_table('finance_balance_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_project_ulid'), ['project_ulid'], unique=False)

    op.create_table('finance_encumbrance',
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('relieved_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('active','relieved','void')", name='ck_enc_status'),
    sa.CheckConstraint('amount_cents >= 0', name='ck_enc_nonneg'),
    sa.CheckConstraint('relieved_cents <= amount_cents', name='ck_enc_rel_le_amount'),
    sa.CheckConstraint('relieved_cents >= 0', name='ck_enc_rel_nonneg'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_encumbrance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_decision_fingerprint'), ['decision_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_source_ref_ulid'), ['source_ref_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_encumbrance_status'), ['status'], unique=False)

    op.create_table('finance_fund',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('restriction', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("restriction in ('unrestricted','temp','perm')", name='ck_fund_restriction'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_fund', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_fund_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_fund_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_fund_restriction'), ['restriction'], unique=False)

    op.create_table('finance_journal',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('external_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('happened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('posted_at_utc', sa.String(length=30), nullable=False),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_journal_external_ref_ulid'), ['external_ref_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_source'), ['source'], unique=False)

    op.create_table('finance_period',
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('open','soft_closed','closed')", name='ck_period_status'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_period_period_key'), ['period_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_period_status'), ['status'], unique=False)

    op.create_table('finance_project',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_project_active'), ['active'], unique=False)

    op.create_table('finance_reserve',
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('active','released','void')", name='ck_reserve_status'),
    sa.CheckConstraint('amount_cents >= 0', name='ck_reserve_nonneg'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_reserve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_reserve_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reserve_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reserve_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reserve_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reserve_source_ref_ulid'), ['source_ref_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reserve_status'), ['status'], unique=False)

    op.create_table('finance_stat_metric',
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('metric_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('period_key', 'metric_code', 'source', 'source_ref_ulid', name='uq_stat_dedupe')
    )
    with op.batch_alter_table('finance_stat_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_stat_metric_metric_code'), ['metric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_stat_metric_period_key'), ['period_key'], unique=False)

    op.create_table('finance_grant',
    sa.Column('fund_id', sa.String(length=26), nullable=False),
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('amount_awarded_cents', sa.Integer(), nullable=False),
    sa.Column('match_required_cents', sa.Integer(), nullable=False),
    sa.Column('start_on', sa.String(length=10), nullable=False),
    sa.Column('end_on', sa.String(length=10), nullable=False),
    sa.Column('reporting_frequency', sa.String(length=16), nullable=False),
    sa.Column('allowable_categories_raw', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("reporting_frequency in ('monthly','quarterly','semiannual','annual','end_of_term')", name='ck_grant_reporting_frequency'),
    sa.ForeignKeyConstraint(['fund_id'], ['finance_fund.ulid'], ),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_grant_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_reporting_frequency'), ['reporting_frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_sponsor_ulid'), ['sponsor_ulid'], unique=False)

    op.create_table('finance_journal_line',
    sa.Column('journal_ulid', sa.String(length=26), nullable=False),
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=24), nullable=False),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('amount_cents != 0', name='ck_line_nonzero'),
    sa.ForeignKeyConstraint(['journal_ulid'], ['finance_journal.ulid'], ),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('journal_ulid', 'seq', name='uq_journalline_seq')
    )
    with op.batch_alter_table('finance_journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_journal_line_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_journal_ulid'), ['journal_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_project_ulid'), ['project_ulid'], unique=False)

    op.create_table('project_project',
    sa.Column('project_title', sa.String(length=100), nullable=False),
    sa.Column('fund_ulid', sa.String(length=26), nullable=True),
    sa.Column('funding_profile_key', sa.String(length=32), nullable=True),
    sa.Column('owner_ulid', sa.String(length=26), nullable=True),
    sa.Column('phase_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['owner_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.create_index('ix_project_fund', ['fund_ulid'], unique=False)
        batch_op.create_index('ix_project_funding_profile', ['funding_profile_key'], unique=False)
        batch_op.create_index('ix_project_owner', ['owner_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_owner_ulid'), ['owner_ulid'], unique=False)
        batch_op.create_index('ix_project_status', ['status'], unique=False)
        batch_op.create_index('ix_project_title', ['project_title'], unique=False)

    op.create_table('finance_reimbursement',
    sa.Column('grant_id', sa.String(length=26), nullable=False),
    sa.Column('submitted_on', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('draft','submitted','approved','paid','void')", name='ck_reimbursement_status'),
    sa.ForeignKeyConstraint(['grant_id'], ['finance_grant.ulid'], ),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_reimbursement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_reimbursement_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reimbursement_status'), ['status'], unique=False)

    op.create_table('funding_plan',
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=True),
    sa.Column('fund_archetype_key', sa.String(length=32), nullable=True),
    sa.Column('expected_amount_cents', sa.Integer(), nullable=True),
    sa.Column('is_in_kind', sa.Boolean(), nullable=False),
    sa.Column('expected_sponsor_hint', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('project_ulid', sa.String(length=26), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('expected_amount_cents IS NULL OR expected_amount_cents >= 0', name='ck_funding_plan_expected_nonneg'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('funding_plan', schema=None) as batch_op:
        batch_op.create_index('ix_funding_plan_archetype', ['fund_archetype_key'], unique=False)
        batch_op.create_index('ix_funding_plan_is_in_kind', ['is_in_kind'], unique=False)
        batch_op.create_index('ix_funding_plan_project', ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_plan_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index('ix_funding_plan_source_kind', ['source_kind'], unique=False)

    op.create_table('project_task',
    sa.Column('project_ulid', sa.String(length=26), nullable=False),
    sa.Column('task_title', sa.String(length=100), nullable=False),
    sa.Column('task_detail', sa.String(length=254), nullable=True),
    sa.Column('task_kind', sa.String(length=32), nullable=True),
    sa.Column('estimate_cents', sa.Integer(), nullable=True),
    sa.Column('hours_est_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('assigned_to_ulid', sa.String(length=26), nullable=True),
    sa.Column('due_at_utc', sa.String(length=30), nullable=True),
    sa.Column('done_at_utc', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('estimate_cents IS NULL OR estimate_cents >= 0', name='ck_task_estimate_nonneg'),
    sa.CheckConstraint('hours_est_minutes IS NULL OR hours_est_minutes >= 0', name='ck_task_hours_nonneg'),
    sa.ForeignKeyConstraint(['assigned_to_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_assigned_to_ulid'), ['assigned_to_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index('ix_task_assignee', ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_task_kind', ['task_kind'], unique=False)
        batch_op.create_index('ix_task_project', ['project_ulid'], unique=False)
        batch_op.create_index('ix_task_status', ['status'], unique=False)
        batch_op.create_index('ix_task_title', ['task_title'], unique=False)

    op.create_table('calendar',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=False),
    sa.Column('location_txt', sa.String(length=100), nullable=True),
    sa.Column('notes_txt', sa.String(length=255), nullable=True),
    sa.Column('color_label', sa.String(length=16), nullable=True),
    sa.Column('starts_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ends_at_utc', sa.String(length=30), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rrule', sa.String(length=200), nullable=True),
    sa.Column('recurrence_exdates_json', sa.JSON(), nullable=True),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('task_ulid', sa.String(length=26), nullable=True),
    sa.Column('owner_ulid', sa.String(length=26), nullable=True),
    sa.Column('assigned_to_ulid', sa.String(length=26), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('reminders_json', sa.JSON(), nullable=True),
    sa.Column('done_at_utc', sa.String(length=30), nullable=True),
    sa.Column('canceled_at_utc', sa.String(length=30), nullable=True),
    sa.Column('archived_at_utc', sa.String(length=30), nullable=True),
    sa.Column('archived_by_actor', sa.String(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('(starts_at_utc IS NULL OR ends_at_utc IS NULL) OR (starts_at_utc <= ends_at_utc)', name='ck_calendar_time_window_valid'),
    sa.ForeignKeyConstraint(['assigned_to_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_ulid'], ['project_task.ulid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_assigned_to_ulid'), ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_calendar_assignee', ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_calendar_event', ['event_title'], unique=False)
        batch_op.create_index('ix_calendar_owner', ['owner_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_owner_ulid'), ['owner_ulid'], unique=False)
        batch_op.create_index('ix_calendar_project', ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index('ix_calendar_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_task_ulid'), ['task_ulid'], unique=False)
        batch_op.create_index('ix_calendar_time_window', ['starts_at_utc', 'ends_at_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_time_window')
        batch_op.drop_index(batch_op.f('ix_calendar_task_ulid'))
        batch_op.drop_index('ix_calendar_status')
        batch_op.drop_index(batch_op.f('ix_calendar_project_ulid'))
        batch_op.drop_index('ix_calendar_project')
        batch_op.drop_index(batch_op.f('ix_calendar_owner_ulid'))
        batch_op.drop_index('ix_calendar_owner')
        batch_op.drop_index('ix_calendar_event')
        batch_op.drop_index('ix_calendar_assignee')
        batch_op.drop_index(batch_op.f('ix_calendar_assigned_to_ulid'))

    op.drop_table('calendar')
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_title')
        batch_op.drop_index('ix_task_status')
        batch_op.drop_index('ix_task_project')
        batch_op.drop_index('ix_task_kind')
        batch_op.drop_index('ix_task_assignee')
        batch_op.drop_index(batch_op.f('ix_project_task_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_project_task_assigned_to_ulid'))

    op.drop_table('project_task')
    with op.batch_alter_table('funding_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_funding_plan_source_kind')
        batch_op.drop_index(batch_op.f('ix_funding_plan_project_ulid'))
        batch_op.drop_index('ix_funding_plan_project')
        batch_op.drop_index('ix_funding_plan_is_in_kind')
        batch_op.drop_index('ix_funding_plan_archetype')

    op.drop_table('funding_plan')
    with op.batch_alter_table('finance_reimbursement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_reimbursement_status'))
        batch_op.drop_index(batch_op.f('ix_finance_reimbursement_grant_id'))

    op.drop_table('finance_reimbursement')
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_title')
        batch_op.drop_index('ix_project_status')
        batch_op.drop_index(batch_op.f('ix_project_project_owner_ulid'))
        batch_op.drop_index('ix_project_owner')
        batch_op.drop_index('ix_project_funding_profile')
        batch_op.drop_index('ix_project_fund')

    op.drop_table('project_project')
    with op.batch_alter_table('finance_journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_journal_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_funding_demand_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_account_code'))

    op.drop_table('finance_journal_line')
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_grant_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_reporting_frequency'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_fund_id'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_active'))

    op.drop_table('finance_grant')
    with op.batch_alter_table('finance_stat_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_stat_metric_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_stat_metric_metric_code'))

    op.drop_table('finance_stat_metric')
    with op.batch_alter_table('finance_reserve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_reserve_status'))
        batch_op.drop_index(batch_op.f('ix_finance_reserve_source_ref_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_reserve_source'))
        batch_op.drop_index(batch_op.f('ix_finance_reserve_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_reserve_funding_demand_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_reserve_fund_code'))

    op.drop_table('finance_reserve')
    with op.batch_alter_table('finance_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_project_active'))

    op.drop_table('finance_project')
    with op.batch_alter_table('finance_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_period_status'))
        batch_op.drop_index(batch_op.f('ix_finance_period_period_key'))

    op.drop_table('finance_period')
    with op.batch_alter_table('finance_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_journal_source'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_funding_demand_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_external_ref_ulid'))

    op.drop_table('finance_journal')
    with op.batch_alter_table('finance_fund', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_fund_restriction'))
        batch_op.drop_index(batch_op.f('ix_finance_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_fund_active'))

    op.drop_table('finance_fund')
    with op.batch_alter_table('finance_encumbrance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_status'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_source_ref_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_source'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_funding_demand_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_encumbrance_decision_fingerprint'))

    op.drop_table('finance_encumbrance')
    with op.batch_alter_table('finance_balance_monthly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_account_code'))

    op.drop_table('finance_balance_monthly')
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_account_type'))
        batch_op.drop_index(batch_op.f('ix_finance_account_code'))
        batch_op.drop_index(batch_op.f('ix_finance_account_active'))

    op.drop_table('finance_account')
    op.drop_table('admin_cron_status')
    # ### end Alembic commands ###
