"""move DOB_era

Revision ID: 3212e633e069
Revises: cfe2c4399db9
Create Date: 2026-02-10 15:57:33.600004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3212e633e069'
down_revision = 'cfe2c4399db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_eligibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('era', sa.String(length=16), nullable=True))

    with op.batch_alter_table('entity_person', schema=None) as batch_op:
        batch_op.drop_column('branch')
        batch_op.drop_column('era')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('era', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=4), nullable=True))

    with op.batch_alter_table('customer_eligibility', schema=None) as batch_op:
        batch_op.drop_column('era')
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
