"""time_now_std cron_table

Revision ID: 328430b2b208
Revises: ee831be61a9c
Create Date: 2025-09-28 21:20:56.526993

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "328430b2b208"
down_revision = "ee831be61a9c"
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cron_status",
        sa.Column("job_name", sa.TEXT(), nullable=True),
        sa.Column("last_success_utc", sa.DATETIME(), nullable=True),
        sa.Column("last_error_utc", sa.DATETIME(), nullable=True),
        sa.Column("last_error", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("job_name"),
    )
    # ### end Alembic commands ###
