"""empty message

Revision ID: 3f0f90ac87fc
Revises: 51426720172f
Create Date: 2026-03-16 15:44:33.420323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f0f90ac87fc"
down_revision = "51426720172f"
branch_labels = "Added_ops_float_table"
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finance_ops_float",
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("support_mode", sa.String(length=16), nullable=False),
        sa.Column(
            "source_funding_demand_ulid", sa.String(length=26), nullable=False
        ),
        sa.Column("source_project_ulid", sa.String(length=26), nullable=True),
        sa.Column(
            "dest_funding_demand_ulid", sa.String(length=26), nullable=False
        ),
        sa.Column("dest_project_ulid", sa.String(length=26), nullable=True),
        sa.Column("fund_code", sa.String(length=32), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "parent_ops_float_ulid", sa.String(length=26), nullable=True
        ),
        sa.Column(
            "decision_fingerprint", sa.String(length=64), nullable=True
        ),
        sa.Column("source_ref_ulid", sa.String(length=26), nullable=True),
        sa.Column("memo", sa.String(length=160), nullable=True),
        sa.Column("ulid", sa.String(length=26), nullable=False),
        sa.Column("created_at_utc", sa.String(length=30), nullable=False),
        sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "action in ('allocate','repay','forgive')",
            name="ck_ops_float_action",
        ),
        sa.CheckConstraint(
            "status in ('active','void')", name="ck_ops_float_status"
        ),
        sa.CheckConstraint(
            "support_mode in ('seed','backfill','bridge')",
            name="ck_ops_float_mode",
        ),
        sa.CheckConstraint("amount_cents >= 0", name="ck_ops_float_nonneg"),
        sa.PrimaryKeyConstraint("ulid"),
    )
    with op.batch_alter_table("finance_ops_float", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_action"),
            ["action"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_decision_fingerprint"),
            ["decision_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_dest_funding_demand_ulid"),
            ["dest_funding_demand_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_dest_project_ulid"),
            ["dest_project_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_fund_code"),
            ["fund_code"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_parent_ops_float_ulid"),
            ["parent_ops_float_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_source_funding_demand_ulid"),
            ["source_funding_demand_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_source_project_ulid"),
            ["source_project_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_source_ref_ulid"),
            ["source_ref_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_status"),
            ["status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_finance_ops_float_support_mode"),
            ["support_mode"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finance_ops_float", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finance_ops_float_support_mode"))
        batch_op.drop_index(batch_op.f("ix_finance_ops_float_status"))
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_source_ref_ulid")
        )
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_source_project_ulid")
        )
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_source_funding_demand_ulid")
        )
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_parent_ops_float_ulid")
        )
        batch_op.drop_index(batch_op.f("ix_finance_ops_float_fund_code"))
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_dest_project_ulid")
        )
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_dest_funding_demand_ulid")
        )
        batch_op.drop_index(
            batch_op.f("ix_finance_ops_float_decision_fingerprint")
        )
        batch_op.drop_index(batch_op.f("ix_finance_ops_float_action"))

    op.drop_table("finance_ops_float")
    # ### end Alembic commands ###
