"""empty message

Revision ID: 488a7f31d9a8
Revises: bc364c7e43e1
Create Date: 2026-04-22 13:58:48.950601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '488a7f31d9a8'
down_revision = 'bc364c7e43e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_alert',
    sa.Column('source_slice', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('admin_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=False),
    sa.Column('resolution_target_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('admin_alert', schema=None) as batch_op:
        batch_op.create_index('ix_admin_alert_active', ['admin_status', 'updated_at_utc'], unique=False)
        batch_op.create_index('ix_admin_alert_request_reason', ['request_id', 'reason_code'], unique=False)
        batch_op.create_index('ix_admin_alert_target_reason', ['target_ulid', 'reason_code'], unique=False)

    op.create_table('admin_alert_archive',
    sa.Column('original_alert_ulid', sa.String(length=26), nullable=False),
    sa.Column('source_slice', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('admin_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=False),
    sa.Column('resolution_target_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('archived_at_utc', sa.String(length=30), nullable=False),
    sa.Column('archive_reason', sa.String(length=64), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('original_alert_ulid')
    )
    with op.batch_alter_table('admin_alert_archive', schema=None) as batch_op:
        batch_op.create_index('ix_admin_alert_archive_archived_at', ['archived_at_utc'], unique=False)
        batch_op.create_index('ix_admin_alert_archive_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_admin_alert_archive_source_reason', ['source_slice', 'reason_code'], unique=False)

    with op.batch_alter_table('admin_inbox_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_inbox_archive_archived_at'))
        batch_op.drop_index(batch_op.f('ix_admin_inbox_archive_source'))
        batch_op.drop_index(batch_op.f('ix_admin_inbox_source_ref_ulid'))

    op.drop_table('admin_inbox_archive')
    with op.batch_alter_table('admin_inbox_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_inbox_item_active'))

    op.drop_table('admin_inbox_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_inbox_item',
    sa.Column('source_slice', sa.VARCHAR(length=64), nullable=False),
    sa.Column('issue_kind', sa.VARCHAR(length=128), nullable=False),
    sa.Column('source_ref_ulid', sa.VARCHAR(length=26), nullable=False),
    sa.Column('subject_ref_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('source_status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('admin_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('workflow_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('resolution_route', sa.VARCHAR(length=200), nullable=False),
    sa.Column('context_json', sqlite.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('close_reason', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dedupe_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ulid', sa.VARCHAR(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('admin_inbox_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_inbox_item_active'), ['admin_status', 'severity', 'updated_at_utc'], unique=False)

    op.create_table('admin_inbox_archive',
    sa.Column('original_inbox_ulid', sa.VARCHAR(length=26), nullable=False),
    sa.Column('source_slice', sa.VARCHAR(length=64), nullable=False),
    sa.Column('issue_kind', sa.VARCHAR(length=128), nullable=False),
    sa.Column('source_ref_ulid', sa.VARCHAR(length=26), nullable=False),
    sa.Column('subject_ref_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('source_status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('admin_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('workflow_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('resolution_route', sa.VARCHAR(length=200), nullable=False),
    sa.Column('context_json', sqlite.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('close_reason', sa.VARCHAR(length=64), nullable=True),
    sa.Column('archived_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('archive_reason', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ulid', sa.VARCHAR(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('original_inbox_ulid')
    )
    with op.batch_alter_table('admin_inbox_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_inbox_source_ref_ulid'), ['source_ref_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_inbox_archive_source'), ['source_slice', 'issue_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_inbox_archive_archived_at'), ['archived_at_utc'], unique=False)

    with op.batch_alter_table('admin_alert_archive', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_alert_archive_source_reason')
        batch_op.drop_index('ix_admin_alert_archive_request_id')
        batch_op.drop_index('ix_admin_alert_archive_archived_at')

    op.drop_table('admin_alert_archive')
    with op.batch_alter_table('admin_alert', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_alert_target_reason')
        batch_op.drop_index('ix_admin_alert_request_reason')
        batch_op.drop_index('ix_admin_alert_active')

    op.drop_table('admin_alert')
    # ### end Alembic commands ###
