"""empty message

Revision ID: 4d1977045f3a
Revises: 262009fc4ee7
Create Date: 2026-03-11 20:51:59.488970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1977045f3a'
down_revision = '262009fc4ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_demand',
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('goal_cents', sa.Integer(), nullable=False),
    sa.Column('deadline_date', sa.String(length=30), nullable=True),
    sa.Column('spending_class', sa.String(length=32), nullable=True),
    sa.Column('eligible_fund_keys_json', sa.JSON(), nullable=True),
    sa.Column('tag_any_json', sa.JSON(), nullable=True),
    sa.Column('published_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','funding_in_progress','funded','executing','closed')", name='ck_funding_demand_status'),
    sa.CheckConstraint('goal_cents >= 0', name='ck_funding_demand_goal_nonneg'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.create_index('ix_funding_demand_project_status', ['project_ulid', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_demand_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_demand_status'), ['status'], unique=False)

    op.create_table('project_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=False),
    sa.Column('tag_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tag_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tag_tag_key'), ['tag_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tag_tag_key'))
        batch_op.drop_index(batch_op.f('ix_project_tag_project_ulid'))

    op.drop_table('project_tag')
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_demand_status'))
        batch_op.drop_index(batch_op.f('ix_funding_demand_project_ulid'))
        batch_op.drop_index('ix_funding_demand_project_status')

    op.drop_table('funding_demand')
    # ### end Alembic commands ###
