"""add finance quarantine

Revision ID: 4f31e74dce7b
Revises: 24ff0ac6c03e
Create Date: 2026-04-28 07:24:40.251686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f31e74dce7b'
down_revision = '24ff0ac6c03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_quarantine',
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('scope_ulid', sa.String(length=26), nullable=True),
    sa.Column('scope_label', sa.String(length=200), nullable=True),
    sa.Column('source_issue_ulid', sa.String(length=26), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('posture', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('close_reason', sa.String(length=128), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("posture in ('projection_blocked','posting_blocked','projection_and_posting_blocked')", name='ck_finance_quarantine_posture'),
    sa.CheckConstraint("scope_type in ('global','project','funding_demand','journal','semantic_posting','ops_float')", name='ck_finance_quarantine_scope_type'),
    sa.CheckConstraint("status in ('active','released','superseded')", name='ck_finance_quarantine_status'),
    sa.ForeignKeyConstraint(['source_issue_ulid'], ['finance_admin_issue.ulid'], ),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_quarantine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_quarantine_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index('ix_finance_quarantine_issue_status', ['source_issue_ulid', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index('ix_finance_quarantine_reason_status', ['reason_code', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_finance_quarantine_scope_status', ['scope_type', 'scope_ulid', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_scope_ulid'), ['scope_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_source_issue_ulid'), ['source_issue_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_quarantine_status'), ['status'], unique=False)

    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dedupe_scope', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_finance_admin_issue_dedupe_scope'), ['dedupe_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_admin_issue_dedupe_scope'))
        batch_op.drop_column('dedupe_scope')

    with op.batch_alter_table('finance_quarantine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_status'))
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_source_issue_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_scope_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_scope_type'))
        batch_op.drop_index('ix_finance_quarantine_scope_status')
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_request_id'))
        batch_op.drop_index('ix_finance_quarantine_reason_status')
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_reason_code'))
        batch_op.drop_index('ix_finance_quarantine_issue_status')
        batch_op.drop_index(batch_op.f('ix_finance_quarantine_dedupe_key'))

    op.drop_table('finance_quarantine')
    # ### end Alembic commands ###
