"""empty message

Revision ID: 52b4b6a702b5
Revises: 86728e20915d
Create Date: 2026-03-25 20:24:38.670610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b4b6a702b5'
down_revision = '86728e20915d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('locked_at_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('locked_by_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at_utc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('reset_issued_at_utc', sa.String(length=30), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
        batch_op.drop_column('reset_issued_at_utc')
        batch_op.drop_column('password_changed_at_utc')
        batch_op.drop_column('locked_by_ulid')
        batch_op.drop_column('locked_at_utc')
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
