"""empty message

Revision ID: 5426b725de2d
Revises: fbc6a56bf7c0
Create Date: 2026-04-06 18:35:03.031354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5426b725de2d'
down_revision = 'fbc6a56bf7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restriction_type', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('project_ulid', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('program_income_allowed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('conditions_summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_document_ref', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_finance_grant_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_restriction_type'), ['restriction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_grant_restriction_type'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_project_ulid'))
        batch_op.drop_column('source_document_ref')
        batch_op.drop_column('conditions_summary')
        batch_op.drop_column('program_income_allowed')
        batch_op.drop_column('project_ulid')
        batch_op.drop_column('restriction_type')

    # ### end Alembic commands ###
