"""FRESH governance canonicals + ledger_event

Revision ID: 60d6421682da
Revises: 328430b2b208
Create Date: 2025-10-15 12:56:38.987045

"""
from alembic import op
import sqlalchemy as sa

from app.extensions.contracts import governance


# revision identifiers, used by Alembic.
revision = "60d6421682da"
down_revision = "328430b2b208"
branch_labels = None
depends_on = None


def _has_table(name: str) -> bool:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return insp.has_table(name)


def _drop_fk_if_named(
    table: str, constrained_cols: list[str], referred_table: str
):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    fks = insp.get_foreign_keys(table)
    for fk in fks:
        # Match by columns and target table; SQLite may return name=None
        cols_match = [
            c.lower() for c in fk.get("constrained_columns", [])
        ] == [c.lower() for c in constrained_cols]
        if (
            cols_match
            and fk.get("referred_table", "").lower() == referred_table.lower()
        ):
            name = fk.get("name")
            if name:
                with op.batch_alter_table(table) as batch_op:
                    batch_op.drop_constraint(name, type_="foreignkey")
            # If no name, skip — SQLite can’t drop unnamed FK by name.
            return


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    if not _has_table("admin_cron_status"):
        op.create_table(
            "admin_cron_status",
            sa.Column("job_name", sa.String(length=120), nullable=False),
            sa.Column(
                "last_success_utc", sa.String(length=30), nullable=True
            ),
            sa.Column("last_error_utc", sa.String(length=30), nullable=True),
            sa.Column("last_error", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("job_name"),
        )
    if not _has_table("attachment_attachment"):
        op.create_table(
            "attachment_attachment",
            sa.Column("sha256", sa.String(length=64), nullable=False),
            sa.Column("size_bytes", sa.Integer(), nullable=False),
            sa.Column("mime", sa.String(length=100), nullable=False),
            sa.Column(
                "original_filename", sa.String(length=255), nullable=True
            ),
            sa.Column("storage_key", sa.String(length=300), nullable=False),
            sa.Column("privacy_level", sa.String(length=1), nullable=False),
            sa.Column(
                "retention_policy_code", sa.String(length=32), nullable=True
            ),
            sa.Column("status", sa.String(length=16), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )

    _drop_fk_if_named("entity_address", ["entity_ulid"], "entity_entity")

    if not _has_table("auth_role"):
        op.create_table(
            "auth_role",
            sa.Column("code", sa.String(length=32), nullable=False),
            sa.Column("description", sa.String(length=200), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.DateTime(), nullable=False),
            sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("auth_role", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_auth_role_code"), ["code"], unique=True
            )
    if not _has_table("auth_user"):
        op.create_table(
            "auth_user",
            sa.Column("entity_ulid", sa.String(length=26), nullable=True),
            sa.Column("username", sa.String(length=64), nullable=False),
            sa.Column("email", sa.String(length=254), nullable=False),
            sa.Column("password_hash", sa.String(length=255), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("is_locked", sa.Boolean(), nullable=False),
            sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
            sa.Column("last_login_at_utc", sa.DateTime(), nullable=True),
            sa.Column("created_at_utc", sa.DateTime(), nullable=False),
            sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("auth_user", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_auth_user_email"), ["email"], unique=True
            )
            batch_op.create_index(
                batch_op.f("ix_auth_user_entity_ulid"),
                ["entity_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_auth_user_username"), ["username"], unique=True
            )

    if not _has_table("calendar"):
        op.create_table(
            "calendar",
            sa.Column("id", sa.String(length=26), nullable=False),
            sa.Column("status", sa.String(length=32), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _has_table("gov_canonical_state"):
        op.create_table(
            "gov_canonical_state",
            sa.Column("code", sa.String(length=2), nullable=False),
            sa.Column("name", sa.String(length=64), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.DateTime(), nullable=False),
            sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table(
            "gov_canonical_state", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_gov_canonical_state_code"),
                ["code"],
                unique=True,
            )
    if not _has_table("gov_role_code"):
        op.create_table(
            "gov_role_code",
            sa.Column("code", sa.String(length=32), nullable=False),
            sa.Column("description", sa.String(length=200), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.DateTime(), nullable=False),
            sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("gov_role_code", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_gov_role_code_code"), ["code"], unique=True
            )

    if not _has_table("gov_service_class"):
        op.create_table(
            "gov_service_class",
            sa.Column("code", sa.String(length=32), nullable=False),
            sa.Column("label", sa.String(length=128), nullable=False),
            sa.Column("sort", sa.Integer(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.DateTime(), nullable=False),
            sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table(
            "gov_service_class", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_gov_service_class_code"), ["code"], unique=True
            )
            batch_op.create_index(
                "ix_gov_service_class_sort", ["sort"], unique=False
            )

    if not _has_table("ledger_event"):
        op.create_table(
            "ledger_event",
            sa.Column("type", sa.String(length=64), nullable=False),
            sa.Column("happened_at_utc", sa.DateTime(), nullable=False),
            sa.Column("actor_ulid", sa.String(length=26), nullable=True),
            sa.Column("subject_ulid", sa.String(length=26), nullable=True),
            sa.Column("entity_ulid", sa.String(length=26), nullable=True),
            sa.Column("changed_fields", sa.JSON(), nullable=True),
            sa.Column("meta", sa.JSON(), nullable=True),
            sa.Column("request_id", sa.String(length=36), nullable=True),
            sa.Column("chain_key", sa.String(length=64), nullable=True),
            sa.Column("prev_hash", sa.LargeBinary(length=32), nullable=True),
            sa.Column("hash", sa.LargeBinary(length=32), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("ledger_event", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_ledger_event_actor_ulid"),
                ["actor_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_chain_key"),
                ["chain_key"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_entity_ulid"),
                ["entity_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_happened_at_utc"),
                ["happened_at_utc"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_hash"), ["hash"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_request_id"),
                ["request_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_subject_ulid"),
                ["subject_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_ledger_event_type"), ["type"], unique=False
            )

    if not _has_table("logi_item"):
        op.create_table(
            "logi_item",
            sa.Column("sku", sa.String(length=32), nullable=True),
            sa.Column("sku_cat", sa.String(length=2), nullable=True),
            sa.Column("sku_sub", sa.String(length=3), nullable=True),
            sa.Column("sku_src", sa.String(length=2), nullable=True),
            sa.Column("sku_size", sa.String(length=3), nullable=True),
            sa.Column("sku_color", sa.String(length=3), nullable=True),
            sa.Column("sku_grade", sa.String(length=1), nullable=True),
            sa.Column("sku_seq", sa.Integer(), nullable=True),
            sa.Column(
                "sku_bin_location", sa.String(length=32), nullable=True
            ),
            sa.Column("sku_nsx", sa.String(length=32), nullable=True),
            sa.Column("category", sa.String(length=32), nullable=False),
            sa.Column("name", sa.String(length=160), nullable=False),
            sa.Column("unit", sa.String(length=16), nullable=False),
            sa.Column("condition", sa.String(length=16), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("logi_item", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_logi_item_active"), ["active"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_category"),
                ["category"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku"), ["sku"], unique=True
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_bin_location"),
                ["sku_bin_location"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_cat"), ["sku_cat"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_color"),
                ["sku_color"],
                unique=False,
            )
            batch_op.create_index(
                "ix_logi_item_sku_family",
                [
                    "sku_cat",
                    "sku_sub",
                    "sku_src",
                    "sku_size",
                    "sku_color",
                    "sku_grade",
                ],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_grade"),
                ["sku_grade"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_seq"), ["sku_seq"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_size"),
                ["sku_size"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_src"), ["sku_src"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_logi_item_sku_sub"), ["sku_sub"], unique=False
            )

    if not _has_table("logi_location"):
        op.create_table(
            "logi_location",
            sa.Column("code", sa.String(length=48), nullable=False),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("logi_location", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_logi_location_active"),
                ["active"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_location_code"), ["code"], unique=True
            )

    if not _has_table("attachment_link"):
        op.create_table(
            "attachment_link",
            sa.Column(
                "attachment_ulid", sa.String(length=26), nullable=False
            ),
            sa.Column("slice", sa.String(length=32), nullable=False),
            sa.Column("domain", sa.String(length=32), nullable=False),
            sa.Column("target_ulid", sa.String(length=26), nullable=False),
            sa.Column("note", sa.String(length=120), nullable=True),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("archived_at_utc", sa.String(length=30), nullable=True),
            sa.Column(
                "archived_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["attachment_ulid"],
                ["attachment_attachment.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint(
                "attachment_ulid",
                "slice",
                "domain",
                "target_ulid",
                "archived_at_utc",
                name="uq_active_link",
            ),
        )
        with op.batch_alter_table("attachment_link", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_attachment_link_attachment_ulid"),
                ["attachment_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_attachment_link_domain"),
                ["domain"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_attachment_link_slice"),
                ["slice"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_attachment_link_target_ulid"),
                ["target_ulid"],
                unique=False,
            )
            batch_op.create_index(
                "ix_links_target_domain",
                ["slice", "domain", "target_ulid"],
                unique=False,
            )

    if not _has_table("auth_user_role"):
        op.create_table(
            "auth_user_role",
            sa.Column("user_ulid", sa.String(length=26), nullable=False),
            sa.Column("role_ulid", sa.String(length=26), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["role_ulid"], ["auth_role.ulid"], ondelete="RESTRICT"
            ),
            sa.ForeignKeyConstraint(
                ["user_ulid"], ["auth_user.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint(
                "user_ulid", "role_ulid", name="uq_auth_user_role_pair"
            ),
        )
        with op.batch_alter_table("auth_user_role", schema=None) as batch_op:
            batch_op.create_index(
                "ix_auth_user_role_role", ["role_ulid"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_auth_user_role_role_ulid"),
                ["role_ulid"],
                unique=False,
            )
            batch_op.create_index(
                "ix_auth_user_role_user", ["user_ulid"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_auth_user_role_user_ulid"),
                ["user_ulid"],
                unique=False,
            )

    if not _has_table("customer_customer"):
        op.create_table(
            "customer_customer",
            sa.Column("entity_ulid", sa.String(length=26), nullable=False),
            sa.Column("tier1_min", sa.Integer(), nullable=True),
            sa.Column("tier2_min", sa.Integer(), nullable=True),
            sa.Column("tier3_min", sa.Integer(), nullable=True),
            sa.Column("flag_tier1_immediate", sa.Boolean(), nullable=False),
            sa.Column("watchlist", sa.Boolean(), nullable=False),
            sa.Column("status", sa.String(length=24), nullable=False),
            sa.Column("first_seen_utc", sa.String(length=30), nullable=True),
            sa.Column("last_touch_utc", sa.String(length=30), nullable=True),
            sa.Column(
                "last_needs_update_utc", sa.String(length=30), nullable=True
            ),
            sa.Column(
                "last_needs_tier_updated", sa.String(length=8), nullable=True
            ),
            sa.Column("flag_reason", sa.String(length=120), nullable=True),
            sa.Column(
                "watchlist_since_utc", sa.String(length=30), nullable=True
            ),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["entity_ulid"], ["entity_entity.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint("entity_ulid", name="uq_customer_entity"),
        )
        with op.batch_alter_table(
            "customer_customer", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_customer_customer_entity_ulid"),
                ["entity_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_customer_flag_tier1_immediate"),
                ["flag_tier1_immediate"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_customer_status"),
                ["status"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_customer_tier1_min"),
                ["tier1_min"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_customer_tier2_min"),
                ["tier2_min"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_customer_watchlist"),
                ["watchlist"],
                unique=False,
            )

    if not _has_table("logi_batch"):
        op.create_table(
            "logi_batch",
            sa.Column("item_ulid", sa.String(length=26), nullable=False),
            sa.Column("source", sa.String(length=24), nullable=False),
            sa.Column(
                "source_entity_ulid", sa.String(length=26), nullable=True
            ),
            sa.Column(
                "received_at_utc", sa.String(length=30), nullable=False
            ),
            sa.Column("note", sa.String(length=160), nullable=True),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.ForeignKeyConstraint(
                ["item_ulid"], ["logi_item.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("logi_batch", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_logi_batch_item_ulid"),
                ["item_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_batch_source"), ["source"], unique=False
            )

    if not _has_table("logi_stock"):
        op.create_table(
            "logi_stock",
            sa.Column("item_ulid", sa.String(length=26), nullable=False),
            sa.Column("location_ulid", sa.String(length=26), nullable=False),
            sa.Column("unit", sa.String(length=16), nullable=False),
            sa.Column("qty_on_hand", sa.Integer(), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["item_ulid"], ["logi_item.ulid"], ondelete="RESTRICT"
            ),
            sa.ForeignKeyConstraint(
                ["location_ulid"], ["logi_location.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint(
                "item_ulid", "location_ulid", name="uq_stock_item_location"
            ),
        )
        with op.batch_alter_table("logi_stock", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_logi_stock_item_ulid"),
                ["item_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_stock_location_ulid"),
                ["location_ulid"],
                unique=False,
            )

    if not _has_table("resource_resource"):
        op.create_table(
            "resource_resource",
            sa.Column("entity_ulid", sa.String(length=26), nullable=False),
            sa.Column("admin_review_required", sa.Boolean(), nullable=False),
            sa.Column(
                "readiness_status", sa.String(length=16), nullable=False
            ),
            sa.Column("mou_status", sa.String(length=16), nullable=False),
            sa.Column("first_seen_utc", sa.String(length=30), nullable=True),
            sa.Column("last_touch_utc", sa.String(length=30), nullable=True),
            sa.Column(
                "capability_last_update_utc",
                sa.String(length=30),
                nullable=True,
            ),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["entity_ulid"], ["entity_entity.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint("entity_ulid", name="uq_resource_entity"),
        )
        with op.batch_alter_table(
            "resource_resource", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_resource_resource_admin_review_required"),
                ["admin_review_required"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_resource_entity_ulid"),
                ["entity_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_resource_mou_status"),
                ["mou_status"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_resource_readiness_status"),
                ["readiness_status"],
                unique=False,
            )

    if not _has_table("sponsor_sponsor"):
        op.create_table(
            "sponsor_sponsor",
            sa.Column("entity_ulid", sa.String(length=26), nullable=False),
            sa.Column("admin_review_required", sa.Boolean(), nullable=False),
            sa.Column(
                "readiness_status", sa.String(length=16), nullable=False
            ),
            sa.Column("mou_status", sa.String(length=16), nullable=False),
            sa.Column("first_seen_utc", sa.String(length=30), nullable=True),
            sa.Column("last_touch_utc", sa.String(length=30), nullable=True),
            sa.Column(
                "capability_last_update_utc",
                sa.String(length=30),
                nullable=True,
            ),
            sa.Column(
                "pledge_last_update_utc", sa.String(length=30), nullable=True
            ),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["entity_ulid"], ["entity_entity.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint("entity_ulid", name="uq_sponsor_entity"),
        )
        with op.batch_alter_table("sponsor_sponsor", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_sponsor_sponsor_admin_review_required"),
                ["admin_review_required"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_sponsor_entity_ulid"),
                ["entity_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_sponsor_mou_status"),
                ["mou_status"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_sponsor_readiness_status"),
                ["readiness_status"],
                unique=False,
            )

    if not _has_table("customer_history"):
        op.create_table(
            "customer_history",
            sa.Column("customer_ulid", sa.String(length=26), nullable=False),
            sa.Column("section", sa.String(length=64), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("data_json", sa.String(), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("version >= 1", name="ck_history_version_pos"),
            sa.ForeignKeyConstraint(
                ["customer_ulid"],
                ["customer_customer.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table(
            "customer_history", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_customer_history_customer_ulid"),
                ["customer_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_customer_history_section"),
                ["section"],
                unique=False,
            )

    if not _has_table("logi_movement"):
        op.create_table(
            "logi_movement",
            sa.Column("batch_ulid", sa.String(length=26), nullable=False),
            sa.Column("item_ulid", sa.String(length=26), nullable=False),
            sa.Column("kind", sa.String(length=16), nullable=False),
            sa.Column("quantity", sa.Integer(), nullable=False),
            sa.Column("unit", sa.String(length=16), nullable=False),
            sa.Column(
                "happened_at_utc", sa.String(length=30), nullable=False
            ),
            sa.Column(
                "location_from_ulid", sa.String(length=26), nullable=True
            ),
            sa.Column(
                "location_to_ulid", sa.String(length=26), nullable=True
            ),
            sa.Column("target_ref_ulid", sa.String(length=26), nullable=True),
            sa.Column("note", sa.String(length=160), nullable=True),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("quantity > 0", name="ck_movement_pos_qty"),
            sa.ForeignKeyConstraint(
                ["batch_ulid"], ["logi_batch.ulid"], ondelete="RESTRICT"
            ),
            sa.ForeignKeyConstraint(
                ["item_ulid"], ["logi_item.ulid"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("logi_movement", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_logi_movement_batch_ulid"),
                ["batch_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_movement_item_ulid"),
                ["item_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_movement_kind"), ["kind"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_logi_movement_location_from_ulid"),
                ["location_from_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_movement_location_to_ulid"),
                ["location_to_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_logi_movement_target_ref_ulid"),
                ["target_ref_ulid"],
                unique=False,
            )

    if not _has_table("resource_capability_index"):
        op.create_table(
            "resource_capability_index",
            sa.Column("resource_ulid", sa.String(length=26), nullable=False),
            sa.Column("domain", sa.String(length=48), nullable=False),
            sa.Column("key", sa.String(length=64), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["resource_ulid"],
                ["resource_resource.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint(
                "resource_ulid",
                "domain",
                "key",
                name="uq_res_cap_idx_triplet",
            ),
        )
        with op.batch_alter_table(
            "resource_capability_index", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_resource_capability_index_active"),
                ["active"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_capability_index_domain"),
                ["domain"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_capability_index_key"),
                ["key"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_capability_index_resource_ulid"),
                ["resource_ulid"],
                unique=False,
            )

    if not _has_table("resource_history"):
        op.create_table(
            "resource_history",
            sa.Column("resource_ulid", sa.String(length=26), nullable=False),
            sa.Column("section", sa.String(length=64), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("data_json", sa.String(), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint(
                "version >= 1", name="ck_res_history_version_pos"
            ),
            sa.ForeignKeyConstraint(
                ["resource_ulid"],
                ["resource_resource.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table(
            "resource_history", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_resource_history_resource_ulid"),
                ["resource_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_resource_history_section"),
                ["section"],
                unique=False,
            )

    if not _has_table("sponsor_capability_index"):
        op.create_table(
            "sponsor_capability_index",
            sa.Column("sponsor_ulid", sa.String(length=26), nullable=False),
            sa.Column("domain", sa.String(length=48), nullable=False),
            sa.Column("key", sa.String(length=64), nullable=False),
            sa.Column("active", sa.Boolean(), nullable=False),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.ForeignKeyConstraint(
                ["sponsor_ulid"],
                ["sponsor_sponsor.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
            sa.UniqueConstraint(
                "sponsor_ulid",
                "domain",
                "key",
                name="uq_sponsor_cap_idx_triplet",
            ),
        )
        with op.batch_alter_table(
            "sponsor_capability_index", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_sponsor_capability_index_active"),
                ["active"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_capability_index_domain"),
                ["domain"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_capability_index_key"),
                ["key"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_capability_index_sponsor_ulid"),
                ["sponsor_ulid"],
                unique=False,
            )

    if not _has_table("sponsor_history"):
        op.create_table(
            "sponsor_history",
            sa.Column("sponsor_ulid", sa.String(length=26), nullable=False),
            sa.Column("section", sa.String(length=64), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("data_json", sa.String(), nullable=False),
            sa.Column("created_at_utc", sa.String(length=30), nullable=False),
            sa.Column(
                "created_by_actor", sa.String(length=26), nullable=True
            ),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint(
                "version >= 1", name="ck_sponsor_hist_version_pos"
            ),
            sa.ForeignKeyConstraint(
                ["sponsor_ulid"],
                ["sponsor_sponsor.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table("sponsor_history", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_sponsor_history_section"),
                ["section"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_history_sponsor_ulid"),
                ["sponsor_ulid"],
                unique=False,
            )

    if not _has_table("sponsor_pledge_index"):
        op.create_table(
            "sponsor_pledge_index",
            sa.Column("sponsor_ulid", sa.String(length=26), nullable=False),
            sa.Column("pledge_ulid", sa.String(length=26), nullable=False),
            sa.Column("type", sa.String(length=16), nullable=False),
            sa.Column("status", sa.String(length=16), nullable=False),
            sa.Column("has_restriction", sa.Boolean(), nullable=False),
            sa.Column("est_value_number", sa.Integer(), nullable=True),
            sa.Column("currency", sa.String(length=8), nullable=True),
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
            sa.Column("ulid", sa.String(length=26), nullable=False),
            sa.CheckConstraint("length(ulid) = 26", name="ck_ulid_len_26"),
            sa.ForeignKeyConstraint(
                ["sponsor_ulid"],
                ["sponsor_sponsor.ulid"],
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("ulid"),
        )
        with op.batch_alter_table(
            "sponsor_pledge_index", schema=None
        ) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_sponsor_pledge_index_has_restriction"),
                ["has_restriction"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_pledge_index_pledge_ulid"),
                ["pledge_ulid"],
                unique=True,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_pledge_index_sponsor_ulid"),
                ["sponsor_ulid"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_pledge_index_status"),
                ["status"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_sponsor_pledge_index_type"),
                ["type"],
                unique=False,
            )


def _drop_table_if_exists(user_roles: str):
    if _has_table(user_roles):
        op.drop_table("user_roles")


def _drop_table_if_exists(governance_office: str):
    if _has_table(governance_office):
        op.drop_table("governance_office")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))


def _drop_table_if_exists(roles: str):
    if _has_table(roles):
        op.drop_table("roles")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))


def _drop_table_if_exists(users: str):
    if _has_table(users):
        op.drop_table("users")


def _drop_table_if_exists(governance_policy: str):
    if _has_table(governance_policy):
        oop.drop_table("governance_policy")
    with op.batch_alter_table(
        "resources_assignment", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_resources_assignment_ref_event_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_resources_assignment_ref_issuance_id")
        )
        batch_op.drop_index(batch_op.f("ix_resources_assignment_resource_id"))


def _drop_table_if_exists(resources_assignment: str):
    if _has_table(resources_assignment):
        op.drop_table("resources_assignment")


def _drop_table_if_exists(governance_officer_term: str):
    if _has_table(governance_officer_term):
        op.drop_table("governance_officer_term")


def _drop_table_if_exists(resources_location: str):
    if _has_table(resources_location):
        op.drop_table("resources_location")
    with op.batch_alter_table("transactions_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_customer"))
        batch_op.drop_index(batch_op.f("ix_ledger_hash"))
        batch_op.drop_index(batch_op.f("ix_ledger_slice_when"))
        batch_op.drop_index(batch_op.f("ix_ledger_type"))
        batch_op.drop_index(batch_op.f("ix_ledger_when"))


def _drop_table_if_exists(transactions_ledger: str):
    if _has_table(transactions_ledger):
        op.drop_table("transactions_ledger")
    with op.batch_alter_table("resources_resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resources_resource_code"))


def _drop_table_if_exists(resources_resource: str):
    if _has_table(resources_resource):
        op.drop_table("resources_resource")


def _drop_table_if_exists(governance_authorization: str):
    if _has_table(governance_authorization):
        op.drop_table("governance_authorization")
    with op.batch_alter_table("entity_address", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("entity_ulid", sa.String(length=26), nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_physical", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_postal", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("postal_code", sa.String(length=10), nullable=False)
        )
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.alter_column(
            "address1",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=80),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "address2",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=80),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "city",
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=60),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            batch_op.f("ux_address_primary_by_purpose"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_entity_address_entity_ulid"),
            ["entity_ulid"],
            unique=False,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "entity_entity",
            ["entity_ulid"],
            ["ulid"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("purpose")
        batch_op.drop_column("id")
        batch_op.drop_column("entity_id")
        batch_op.drop_column("tz")
        batch_op.drop_column("postal")
        batch_op.drop_column("is_primary")

    with op.batch_alter_table("entity_contact", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("entity_ulid", sa.String(length=26), nullable=False)
        )
        batch_op.add_column(
            sa.Column("email", sa.String(length=254), nullable=True)
        )
        batch_op.add_column(
            sa.Column("phone", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.alter_column(
            "is_primary",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            batch_op.f("ux_contact_primary_per_kind"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_entity_contact_entity_ulid"),
            ["entity_ulid"],
            unique=False,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "entity_entity",
            ["entity_ulid"],
            ["ulid"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("entity_id")
        batch_op.drop_column("id")
        batch_op.drop_column("value")
        batch_op.drop_column("kind")

    with op.batch_alter_table("entity_entity", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.alter_column(
            "created_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at_utc",
            existing_type=sa.DATETIME(),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    with op.batch_alter_table("entity_org", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("entity_ulid", sa.String(length=26), nullable=False)
        )
        batch_op.add_column(
            sa.Column("dba_name", sa.String(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.alter_column(
            "legal_name",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_entity_org_ein"))
        batch_op.create_index(
            batch_op.f("ix_entity_org_entity_ulid"),
            ["entity_ulid"],
            unique=False,
        )
        batch_op.create_unique_constraint("uq_org_entity", ["entity_ulid"])
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "entity_entity",
            ["entity_ulid"],
            ["ulid"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("entity_id")
        batch_op.drop_column("doing_business_as")

    with op.batch_alter_table("entity_person", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("entity_ulid", sa.String(length=26), nullable=False)
        )
        batch_op.add_column(
            sa.Column("created_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.alter_column(
            "first_name",
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=40),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_name",
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=60),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "preferred_name",
            existing_type=sa.VARCHAR(length=80),
            type_=sa.String(length=60),
            existing_nullable=True,
        )
        batch_op.create_index(
            batch_op.f("ix_entity_person_entity_ulid"),
            ["entity_ulid"],
            unique=False,
        )
        batch_op.create_unique_constraint("uq_person_entity", ["entity_ulid"])
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "entity_entity",
            ["entity_ulid"],
            ["ulid"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("entity_id")

    with op.batch_alter_table("entity_role", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("entity_ulid", sa.String(length=26), nullable=False)
        )
        batch_op.add_column(
            sa.Column("role", sa.String(length=50), nullable=False)
        )
        batch_op.add_column(
            sa.Column("created_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_at_utc", sa.String(length=30), nullable=False)
        )
        batch_op.add_column(
            sa.Column("ulid", sa.String(length=26), nullable=False)
        )
        batch_op.drop_constraint(batch_op.f("ux_entity_role"), type_="unique")
        batch_op.create_index(
            batch_op.f("ix_entity_role_entity_ulid"),
            ["entity_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_entity_role_role"), ["role"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_entity_role_pair", ["entity_ulid", "role"]
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "entity_entity",
            ["entity_ulid"],
            ["ulid"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("id")
        batch_op.drop_column("entity_id")
        batch_op.drop_column("role_code")
        batch_op.drop_column("granted_at_utc")

    # ### end Alembic commands ###


def downgrade():
    pass

    # ### end Alembic commands ###
