"""empty message

Revision ID: 68846e9c95e4
Revises: 3f0f90ac87fc
Create Date: 2026-03-22 06:31:16.682286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68846e9c95e4'
down_revision = '3f0f90ac87fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_context_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.drop_column('published_context_json')

    # ### end Alembic commands ###
