"""Base schema v2 (all slices)

Revision ID: 742d25a45d89
Revises: 
Create Date: 2025-11-05 22:10:10.571821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742d25a45d89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_cron_status',
    sa.Column('job_name', sa.String(length=120), nullable=False),
    sa.Column('last_success_utc', sa.String(length=30), nullable=True),
    sa.Column('last_error_utc', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('attachment_attachment',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('privacy_level', sa.String(length=1), nullable=False),
    sa.Column('retention_policy_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('attachment_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_attachment_sha256'), ['sha256'], unique=True)

    op.create_table('auth_role',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('auth_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_role_code'), ['code'], unique=True)

    op.create_table('auth_user',
    sa.Column('entity_ulid', sa.String(length=26), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_user_entity_ulid'), ['entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_user_username'), ['username'], unique=True)

    op.create_table('entity_entity',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    op.create_table('finance_account',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("type in ('asset','liability','net_assets','revenue','expense')", name='ck_account_type'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_account_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_account_type'), ['type'], unique=False)

    op.create_table('finance_balance_monthly',
    sa.Column('account_code', sa.String(length=24), nullable=False),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('debits_cents', sa.Integer(), nullable=False),
    sa.Column('credits_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('account_code', 'fund_code', 'project_ulid', 'period_key', name='uq_balance_key')
    )
    with op.batch_alter_table('finance_balance_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_monthly_project_ulid'), ['project_ulid'], unique=False)

    op.create_table('finance_fund',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('restriction', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("restriction in ('unrestricted','temp','perm')", name='ck_fund_restriction'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_fund', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_fund_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_fund_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_fund_restriction'), ['restriction'], unique=False)

    op.create_table('finance_journal',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('happened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('posted_at_utc', sa.String(length=30), nullable=False),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_journal_external_ref_ulid'), ['external_ref_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_source'), ['source'], unique=False)

    op.create_table('finance_period',
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('open','soft_closed','closed')", name='ck_period_status'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_period_period_key'), ['period_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_period_status'), ['status'], unique=False)

    op.create_table('finance_project',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_project_active'), ['active'], unique=False)

    op.create_table('finance_stat_metric',
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('metric_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('period_key', 'metric_code', 'source', 'source_ref_ulid', name='uq_stat_dedupe')
    )
    with op.batch_alter_table('finance_stat_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_stat_metric_metric_code'), ['metric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_stat_metric_period_key'), ['period_key'], unique=False)

    op.create_table('gov_canonical_state',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('gov_canonical_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gov_canonical_state_code'), ['code'], unique=True)

    op.create_table('gov_role_code',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('gov_role_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gov_role_code_code'), ['code'], unique=True)

    op.create_table('gov_service_class',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('gov_service_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gov_service_class_code'), ['code'], unique=True)
        batch_op.create_index('ix_gov_service_class_sort', ['sort'], unique=False)

    op.create_table('governance_policy',
    sa.Column('namespace', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.Column('schema_json', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('namespace', 'key', 'version', name='uq_governance_policy_version')
    )
    with op.batch_alter_table('governance_policy', schema=None) as batch_op:
        batch_op.create_index('ix_governance_policy_active', ['namespace', 'key', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_policy_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_policy_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_policy_namespace'), ['namespace'], unique=False)

    op.create_table('ledger_event',
    sa.Column('chain_key', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=26), nullable=False),
    sa.Column('happened_at_utc', sa.String(length=30), nullable=True),
    sa.Column('refs_json', sa.Text(), nullable=True),
    sa.Column('changed_json', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('prev_hash_hex', sa.String(length=64), nullable=True),
    sa.Column('curr_hash_hex', sa.String(length=64), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('ledger_event', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_event_chain_key_id', ['chain_key'], unique=False)
        batch_op.create_index('ix_ledger_event_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_ledger_event_request_id', ['request_id'], unique=False)

    op.create_table('logi_item',
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('sku_cat', sa.String(length=2), nullable=False),
    sa.Column('sku_sub', sa.String(length=3), nullable=False),
    sa.Column('sku_src', sa.String(length=2), nullable=False),
    sa.Column('sku_size', sa.String(length=3), nullable=False),
    sa.Column('sku_color', sa.String(length=3), nullable=False),
    sa.Column('sku_issuance_class', sa.String(length=1), nullable=False),
    sa.Column('sku_seq', sa.Integer(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('logi_item', schema=None) as batch_op:
        batch_op.create_index('ix_item_sku_family', ['sku_cat', 'sku_sub', 'sku_src', 'sku_size', 'sku_color', 'sku_issuance_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_cat'), ['sku_cat'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_color'), ['sku_color'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_issuance_class'), ['sku_issuance_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_size'), ['sku_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_src'), ['sku_src'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_item_sku_sub'), ['sku_sub'], unique=False)

    op.create_table('logi_location',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('code')
    )
    op.create_table('attachment_link',
    sa.Column('attachment_ulid', sa.String(length=26), nullable=False),
    sa.Column('slice', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('target_ulid', sa.String(length=26), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('archived_at_utc', sa.String(length=30), nullable=True),
    sa.Column('archived_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['attachment_ulid'], ['attachment_attachment.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('attachment_ulid', 'slice', 'domain', 'target_ulid', 'archived_at_utc', name='uq_active_link')
    )
    with op.batch_alter_table('attachment_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_link_attachment_ulid'), ['attachment_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_link_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_link_slice'), ['slice'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_link_target_ulid'), ['target_ulid'], unique=False)
        batch_op.create_index('ix_links_target_domain', ['slice', 'domain', 'target_ulid'], unique=False)

    op.create_table('auth_user_role',
    sa.Column('user_ulid', sa.String(length=26), nullable=False),
    sa.Column('role_ulid', sa.String(length=26), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['role_ulid'], ['auth_role.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_ulid'], ['auth_user.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('user_ulid', 'role_ulid', name='uq_auth_user_role_pair')
    )
    with op.batch_alter_table('auth_user_role', schema=None) as batch_op:
        batch_op.create_index('ix_auth_user_role_role', ['role_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_user_role_role_ulid'), ['role_ulid'], unique=False)
        batch_op.create_index('ix_auth_user_role_user', ['user_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_user_role_user_ulid'), ['user_ulid'], unique=False)

    op.create_table('customer_customer',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('tier1_min', sa.Integer(), nullable=True),
    sa.Column('tier2_min', sa.Integer(), nullable=True),
    sa.Column('tier3_min', sa.Integer(), nullable=True),
    sa.Column('flag_tier1_immediate', sa.Boolean(), nullable=False),
    sa.Column('watchlist', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('first_seen_utc', sa.String(length=30), nullable=True),
    sa.Column('last_touch_utc', sa.String(length=30), nullable=True),
    sa.Column('last_needs_update_utc', sa.String(length=30), nullable=True),
    sa.Column('last_needs_tier_updated', sa.String(length=8), nullable=True),
    sa.Column('flag_reason', sa.String(length=120), nullable=True),
    sa.Column('watchlist_since_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('entity_ulid', name='uq_customer_entity')
    )
    with op.batch_alter_table('customer_customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_customer_entity_ulid'), ['entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_flag_tier1_immediate'), ['flag_tier1_immediate'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_tier1_min'), ['tier1_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_tier2_min'), ['tier2_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_customer_watchlist'), ['watchlist'], unique=False)

    op.create_table('entity_address',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('is_physical', sa.Boolean(), nullable=False),
    sa.Column('is_postal', sa.Boolean(), nullable=False),
    sa.Column('address1', sa.String(length=80), nullable=False),
    sa.Column('address2', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(state) = 2', name='ck_state_len_2'),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('entity_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_address_entity_ulid'), ['entity_ulid'], unique=False)

    op.create_table('entity_contact',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('entity_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_contact_entity_ulid'), ['entity_ulid'], unique=False)

    op.create_table('entity_org',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('legal_name', sa.String(length=120), nullable=False),
    sa.Column('dba_name', sa.String(length=120), nullable=True),
    sa.Column('ein', sa.String(length=9), nullable=True),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('ein', name='uq_org_ein'),
    sa.UniqueConstraint('entity_ulid', name='uq_org_entity')
    )
    with op.batch_alter_table('entity_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_org_entity_ulid'), ['entity_ulid'], unique=False)

    op.create_table('entity_person',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('preferred_name', sa.String(length=60), nullable=True),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('entity_ulid', name='uq_person_entity')
    )
    with op.batch_alter_table('entity_person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_person_entity_ulid'), ['entity_ulid'], unique=False)

    op.create_table('entity_role',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('archived_at', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('entity_ulid', 'role', name='uq_entity_role_pair')
    )
    with op.batch_alter_table('entity_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_role_entity_ulid'), ['entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_role_role'), ['role'], unique=False)

    op.create_table('finance_journal_line',
    sa.Column('journal_ulid', sa.String(length=26), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=24), nullable=False),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=160), nullable=True),
    sa.Column('period_key', sa.String(length=7), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('amount_cents != 0', name='ck_line_nonzero'),
    sa.ForeignKeyConstraint(['journal_ulid'], ['finance_journal.ulid'], ),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('journal_ulid', 'seq', name='uq_journalline_seq')
    )
    with op.batch_alter_table('finance_journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_journal_line_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_journal_ulid'), ['journal_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_journal_line_project_ulid'), ['project_ulid'], unique=False)

    op.create_table('logi_batch',
    sa.Column('item_ulid', sa.String(length=26), nullable=False),
    sa.Column('location_ulid', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.ForeignKeyConstraint(['item_ulid'], ['logi_item.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_ulid'], ['logi_location.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('logi_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logi_batch_item_ulid'), ['item_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_batch_location_ulid'), ['location_ulid'], unique=False)

    op.create_table('logi_stock',
    sa.Column('item_ulid', sa.String(length=26), nullable=False),
    sa.Column('location_ulid', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.ForeignKeyConstraint(['item_ulid'], ['logi_item.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_ulid'], ['logi_location.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('logi_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logi_stock_item_ulid'), ['item_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_stock_location_ulid'), ['location_ulid'], unique=False)

    op.create_table('project_project',
    sa.Column('project_title', sa.String(length=100), nullable=False),
    sa.Column('fund_ulid', sa.String(length=26), nullable=True),
    sa.Column('owner_ulid', sa.String(length=26), nullable=True),
    sa.Column('phase_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['owner_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.create_index('ix_project_fund', ['fund_ulid'], unique=False)
        batch_op.create_index('ix_project_owner', ['owner_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_owner_ulid'), ['owner_ulid'], unique=False)
        batch_op.create_index('ix_project_status', ['status'], unique=False)
        batch_op.create_index('ix_project_title', ['project_title'], unique=False)

    op.create_table('resource_resource',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('admin_review_required', sa.Boolean(), nullable=False),
    sa.Column('readiness_status', sa.String(length=16), nullable=False),
    sa.Column('mou_status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_utc', sa.String(length=30), nullable=True),
    sa.Column('last_touch_utc', sa.String(length=30), nullable=True),
    sa.Column('capability_last_update_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('entity_ulid', name='uq_resource_entity')
    )
    with op.batch_alter_table('resource_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_resource_admin_review_required'), ['admin_review_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_resource_entity_ulid'), ['entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_resource_mou_status'), ['mou_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_resource_readiness_status'), ['readiness_status'], unique=False)

    op.create_table('sponsor_sponsor',
    sa.Column('entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('admin_review_required', sa.Boolean(), nullable=False),
    sa.Column('readiness_status', sa.String(length=16), nullable=False),
    sa.Column('mou_status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_utc', sa.String(length=30), nullable=True),
    sa.Column('last_touch_utc', sa.String(length=30), nullable=True),
    sa.Column('capability_last_update_utc', sa.String(length=30), nullable=True),
    sa.Column('pledge_last_update_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entity_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('entity_ulid', name='uq_sponsor_entity')
    )
    with op.batch_alter_table('sponsor_sponsor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_sponsor_admin_review_required'), ['admin_review_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_sponsor_entity_ulid'), ['entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_sponsor_mou_status'), ['mou_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_sponsor_readiness_status'), ['readiness_status'], unique=False)

    op.create_table('customer_eligibility',
    sa.Column('customer_ulid', sa.String(length=26), nullable=False),
    sa.Column('is_veteran_verified', sa.Boolean(), nullable=False),
    sa.Column('veteran_method', sa.String(length=32), nullable=True),
    sa.Column('approved_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('approved_at_utc', sa.String(length=30), nullable=True),
    sa.Column('is_homeless_verified', sa.Boolean(), nullable=False),
    sa.Column('tier1_min', sa.Integer(), nullable=True),
    sa.Column('tier2_min', sa.Integer(), nullable=True),
    sa.Column('tier3_min', sa.Integer(), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("NOT (is_veteran_verified = 1 AND veteran_method = 'other' AND approved_by_ulid IS NULL)", name='ck_ce_other_requires_approval'),
    sa.CheckConstraint("veteran_method IS NULL OR veteran_method IN ('dd214','va_id','state_dl_veteran','other')", name='ck_ce_veteran_method_enum'),
    sa.CheckConstraint('NOT (is_veteran_verified = 0 AND (veteran_method IS NOT NULL OR approved_by_ulid IS NOT NULL OR approved_at_utc IS NOT NULL))', name='ck_ce_unverified_requires_nulls'),
    sa.CheckConstraint('tier1_min IS NULL OR (tier1_min BETWEEN 1 AND 3)', name='ck_el_tier1_range'),
    sa.CheckConstraint('tier2_min IS NULL OR (tier2_min BETWEEN 1 AND 3)', name='ck_el_tier2_range'),
    sa.CheckConstraint('tier3_min IS NULL OR (tier3_min BETWEEN 1 AND 3)', name='ck_el_tier3_range'),
    sa.ForeignKeyConstraint(['customer_ulid'], ['customer_customer.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('customer_ulid', name='uq_customer_eligibility_customer')
    )
    with op.batch_alter_table('customer_eligibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_eligibility_customer_ulid'), ['customer_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_eligibility_is_homeless_verified'), ['is_homeless_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_eligibility_is_veteran_verified'), ['is_veteran_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_eligibility_tier1_min'), ['tier1_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_eligibility_tier2_min'), ['tier2_min'], unique=False)

    op.create_table('customer_history',
    sa.Column('customer_ulid', sa.String(length=26), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_history_version_pos'),
    sa.ForeignKeyConstraint(['customer_ulid'], ['customer_customer.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('customer_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_history_customer_ulid'), ['customer_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_history_section'), ['section'], unique=False)

    op.create_table('logi_movement',
    sa.Column('item_ulid', sa.String(length=26), nullable=False),
    sa.Column('location_ulid', sa.String(length=26), nullable=False),
    sa.Column('batch_ulid', sa.String(length=26), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('happened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('target_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('note', sa.String(length=160), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('quantity>0', name='ck_move_pos_qty'),
    sa.ForeignKeyConstraint(['batch_ulid'], ['logi_batch.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_ulid'], ['logi_item.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_ulid'], ['logi_location.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('logi_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logi_movement_batch_ulid'), ['batch_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_movement_item_ulid'), ['item_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_movement_location_ulid'), ['location_ulid'], unique=False)

    op.create_table('project_task',
    sa.Column('task_title', sa.String(length=100), nullable=False),
    sa.Column('task_detail', sa.String(length=254), nullable=True),
    sa.Column('project_ulid', sa.String(length=26), nullable=False),
    sa.Column('assigned_to_ulid', sa.String(length=26), nullable=True),
    sa.Column('due_at_utc', sa.String(length=30), nullable=True),
    sa.Column('done_at_utc', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_assigned_to_ulid'), ['assigned_to_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index('ix_task_assignee', ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_task_project', ['project_ulid'], unique=False)
        batch_op.create_index('ix_task_status', ['status'], unique=False)
        batch_op.create_index('ix_task_title', ['task_title'], unique=False)

    op.create_table('resource_capability_index',
    sa.Column('resource_ulid', sa.String(length=26), nullable=False),
    sa.Column('domain', sa.String(length=48), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['resource_ulid'], ['resource_resource.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('resource_ulid', 'domain', 'key', name='uq_res_cap_idx_triplet')
    )
    with op.batch_alter_table('resource_capability_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_capability_index_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_capability_index_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_capability_index_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_capability_index_resource_ulid'), ['resource_ulid'], unique=False)

    op.create_table('resource_history',
    sa.Column('resource_ulid', sa.String(length=26), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_res_history_version_pos'),
    sa.ForeignKeyConstraint(['resource_ulid'], ['resource_resource.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('resource_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_history_resource_ulid'), ['resource_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_history_section'), ['section'], unique=False)

    op.create_table('sponsor_allocation',
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('customer_ulid', sa.String(length=26), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('amount_authorized_cents', sa.Integer(), nullable=False),
    sa.Column('approved_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('expires_on_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('amount_authorized_cents >= 0', name='ck_alloc_amount_nonneg'),
    sa.ForeignKeyConstraint(['customer_ulid'], ['entity_entity.ulid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sponsor_ulid'], ['sponsor_sponsor.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('sponsor_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_allocation_approved_by_ulid'), ['approved_by_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_allocation_customer_ulid'), ['customer_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_allocation_sponsor_ulid'), ['sponsor_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_allocation_state'), ['state'], unique=False)

    op.create_table('sponsor_capability_index',
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('domain', sa.String(length=48), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_ulid'], ['sponsor_sponsor.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('sponsor_ulid', 'domain', 'key', name='uq_sponsor_cap_idx_triplet')
    )
    with op.batch_alter_table('sponsor_capability_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_capability_index_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_capability_index_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_capability_index_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_capability_index_sponsor_ulid'), ['sponsor_ulid'], unique=False)

    op.create_table('sponsor_history',
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_sponsor_hist_version_pos'),
    sa.ForeignKeyConstraint(['sponsor_ulid'], ['sponsor_sponsor.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('sponsor_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_history_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_history_sponsor_ulid'), ['sponsor_ulid'], unique=False)

    op.create_table('sponsor_pledge_index',
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('pledge_ulid', sa.String(length=26), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('has_restriction', sa.Boolean(), nullable=False),
    sa.Column('est_value_number', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('length(ulid) = 26', name='ck_ulid_len_26'),
    sa.ForeignKeyConstraint(['sponsor_ulid'], ['sponsor_sponsor.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('sponsor_pledge_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_pledge_index_has_restriction'), ['has_restriction'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_pledge_index_pledge_ulid'), ['pledge_ulid'], unique=True)
        batch_op.create_index(batch_op.f('ix_sponsor_pledge_index_sponsor_ulid'), ['sponsor_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_pledge_index_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_pledge_index_type'), ['type'], unique=False)

    op.create_table('calendar',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=False),
    sa.Column('location_txt', sa.String(length=100), nullable=True),
    sa.Column('notes_txt', sa.String(length=255), nullable=True),
    sa.Column('color_label', sa.String(length=16), nullable=True),
    sa.Column('starts_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ends_at_utc', sa.String(length=30), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rrule', sa.String(length=200), nullable=True),
    sa.Column('recurrence_exdates_json', sa.JSON(), nullable=True),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('task_ulid', sa.String(length=26), nullable=True),
    sa.Column('owner_ulid', sa.String(length=26), nullable=True),
    sa.Column('assigned_to_ulid', sa.String(length=26), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('reminders_json', sa.JSON(), nullable=True),
    sa.Column('done_at_utc', sa.String(length=30), nullable=True),
    sa.Column('canceled_at_utc', sa.String(length=30), nullable=True),
    sa.Column('archived_at_utc', sa.String(length=30), nullable=True),
    sa.Column('archived_by_actor', sa.String(length=26), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('(starts_at_utc IS NULL OR ends_at_utc IS NULL) OR (starts_at_utc <= ends_at_utc)', name='ck_calendar_time_window_valid'),
    sa.ForeignKeyConstraint(['assigned_to_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_ulid'], ['entity_entity.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_ulid'], ['project_task.ulid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_assigned_to_ulid'), ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_calendar_assignee', ['assigned_to_ulid'], unique=False)
        batch_op.create_index('ix_calendar_event', ['event_title'], unique=False)
        batch_op.create_index('ix_calendar_owner', ['owner_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_owner_ulid'), ['owner_ulid'], unique=False)
        batch_op.create_index('ix_calendar_project', ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index('ix_calendar_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_task_ulid'), ['task_ulid'], unique=False)
        batch_op.create_index('ix_calendar_time_window', ['starts_at_utc', 'ends_at_utc'], unique=False)

    op.create_table('logi_issue',
    sa.Column('customer_ulid', sa.String(length=26), nullable=False),
    sa.Column('classification_key', sa.String(length=64), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.String(length=30), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('movement_ulid', sa.String(length=26), nullable=True),
    sa.Column('created_by_actor', sa.String(length=26), nullable=True),
    sa.Column('decision_json', sa.Text(), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.CheckConstraint('quantity>0', name='ck_issue_pos_qty'),
    sa.ForeignKeyConstraint(['movement_ulid'], ['logi_movement.ulid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('logi_issue', schema=None) as batch_op:
        batch_op.create_index('ix_issue_customer_class_time', ['customer_ulid', 'classification_key', 'issued_at'], unique=False)
        batch_op.create_index('ix_issue_customer_issued_at', ['customer_ulid', 'issued_at'], unique=False)
        batch_op.create_index('ix_issue_customer_sku_time', ['customer_ulid', 'sku_code', 'issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_issue_classification_key'), ['classification_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_issue_customer_ulid'), ['customer_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_issue_movement_ulid'), ['movement_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_issue_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_logi_issue_sku_code'), ['sku_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logi_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logi_issue_sku_code'))
        batch_op.drop_index(batch_op.f('ix_logi_issue_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_issue_movement_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_issue_customer_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_issue_classification_key'))
        batch_op.drop_index('ix_issue_customer_sku_time')
        batch_op.drop_index('ix_issue_customer_issued_at')
        batch_op.drop_index('ix_issue_customer_class_time')

    op.drop_table('logi_issue')
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_time_window')
        batch_op.drop_index(batch_op.f('ix_calendar_task_ulid'))
        batch_op.drop_index('ix_calendar_status')
        batch_op.drop_index(batch_op.f('ix_calendar_project_ulid'))
        batch_op.drop_index('ix_calendar_project')
        batch_op.drop_index(batch_op.f('ix_calendar_owner_ulid'))
        batch_op.drop_index('ix_calendar_owner')
        batch_op.drop_index('ix_calendar_event')
        batch_op.drop_index('ix_calendar_assignee')
        batch_op.drop_index(batch_op.f('ix_calendar_assigned_to_ulid'))

    op.drop_table('calendar')
    with op.batch_alter_table('sponsor_pledge_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_pledge_index_type'))
        batch_op.drop_index(batch_op.f('ix_sponsor_pledge_index_status'))
        batch_op.drop_index(batch_op.f('ix_sponsor_pledge_index_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_pledge_index_pledge_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_pledge_index_has_restriction'))

    op.drop_table('sponsor_pledge_index')
    with op.batch_alter_table('sponsor_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_history_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_history_section'))

    op.drop_table('sponsor_history')
    with op.batch_alter_table('sponsor_capability_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_capability_index_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_capability_index_key'))
        batch_op.drop_index(batch_op.f('ix_sponsor_capability_index_domain'))
        batch_op.drop_index(batch_op.f('ix_sponsor_capability_index_active'))

    op.drop_table('sponsor_capability_index')
    with op.batch_alter_table('sponsor_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_allocation_state'))
        batch_op.drop_index(batch_op.f('ix_sponsor_allocation_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_allocation_customer_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_allocation_approved_by_ulid'))

    op.drop_table('sponsor_allocation')
    with op.batch_alter_table('resource_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_history_section'))
        batch_op.drop_index(batch_op.f('ix_resource_history_resource_ulid'))

    op.drop_table('resource_history')
    with op.batch_alter_table('resource_capability_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_capability_index_resource_ulid'))
        batch_op.drop_index(batch_op.f('ix_resource_capability_index_key'))
        batch_op.drop_index(batch_op.f('ix_resource_capability_index_domain'))
        batch_op.drop_index(batch_op.f('ix_resource_capability_index_active'))

    op.drop_table('resource_capability_index')
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_title')
        batch_op.drop_index('ix_task_status')
        batch_op.drop_index('ix_task_project')
        batch_op.drop_index('ix_task_assignee')
        batch_op.drop_index(batch_op.f('ix_project_task_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_project_task_assigned_to_ulid'))

    op.drop_table('project_task')
    with op.batch_alter_table('logi_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logi_movement_location_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_movement_item_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_movement_batch_ulid'))

    op.drop_table('logi_movement')
    with op.batch_alter_table('customer_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_history_section'))
        batch_op.drop_index(batch_op.f('ix_customer_history_customer_ulid'))

    op.drop_table('customer_history')
    with op.batch_alter_table('customer_eligibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_eligibility_tier2_min'))
        batch_op.drop_index(batch_op.f('ix_customer_eligibility_tier1_min'))
        batch_op.drop_index(batch_op.f('ix_customer_eligibility_is_veteran_verified'))
        batch_op.drop_index(batch_op.f('ix_customer_eligibility_is_homeless_verified'))
        batch_op.drop_index(batch_op.f('ix_customer_eligibility_customer_ulid'))

    op.drop_table('customer_eligibility')
    with op.batch_alter_table('sponsor_sponsor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_sponsor_readiness_status'))
        batch_op.drop_index(batch_op.f('ix_sponsor_sponsor_mou_status'))
        batch_op.drop_index(batch_op.f('ix_sponsor_sponsor_entity_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_sponsor_admin_review_required'))

    op.drop_table('sponsor_sponsor')
    with op.batch_alter_table('resource_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_resource_readiness_status'))
        batch_op.drop_index(batch_op.f('ix_resource_resource_mou_status'))
        batch_op.drop_index(batch_op.f('ix_resource_resource_entity_ulid'))
        batch_op.drop_index(batch_op.f('ix_resource_resource_admin_review_required'))

    op.drop_table('resource_resource')
    with op.batch_alter_table('project_project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_title')
        batch_op.drop_index('ix_project_status')
        batch_op.drop_index(batch_op.f('ix_project_project_owner_ulid'))
        batch_op.drop_index('ix_project_owner')
        batch_op.drop_index('ix_project_fund')

    op.drop_table('project_project')
    with op.batch_alter_table('logi_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logi_stock_location_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_stock_item_ulid'))

    op.drop_table('logi_stock')
    with op.batch_alter_table('logi_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logi_batch_location_ulid'))
        batch_op.drop_index(batch_op.f('ix_logi_batch_item_ulid'))

    op.drop_table('logi_batch')
    with op.batch_alter_table('finance_journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_journal_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_line_account_code'))

    op.drop_table('finance_journal_line')
    with op.batch_alter_table('entity_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_role_role'))
        batch_op.drop_index(batch_op.f('ix_entity_role_entity_ulid'))

    op.drop_table('entity_role')
    with op.batch_alter_table('entity_person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_person_entity_ulid'))

    op.drop_table('entity_person')
    with op.batch_alter_table('entity_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_org_entity_ulid'))

    op.drop_table('entity_org')
    with op.batch_alter_table('entity_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_contact_entity_ulid'))

    op.drop_table('entity_contact')
    with op.batch_alter_table('entity_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_address_entity_ulid'))

    op.drop_table('entity_address')
    with op.batch_alter_table('customer_customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_customer_watchlist'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_tier2_min'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_tier1_min'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_status'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_flag_tier1_immediate'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_entity_ulid'))

    op.drop_table('customer_customer')
    with op.batch_alter_table('auth_user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_user_role_user_ulid'))
        batch_op.drop_index('ix_auth_user_role_user')
        batch_op.drop_index(batch_op.f('ix_auth_user_role_role_ulid'))
        batch_op.drop_index('ix_auth_user_role_role')

    op.drop_table('auth_user_role')
    with op.batch_alter_table('attachment_link', schema=None) as batch_op:
        batch_op.drop_index('ix_links_target_domain')
        batch_op.drop_index(batch_op.f('ix_attachment_link_target_ulid'))
        batch_op.drop_index(batch_op.f('ix_attachment_link_slice'))
        batch_op.drop_index(batch_op.f('ix_attachment_link_domain'))
        batch_op.drop_index(batch_op.f('ix_attachment_link_attachment_ulid'))

    op.drop_table('attachment_link')
    op.drop_table('logi_location')
    with op.batch_alter_table('logi_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_sub'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_src'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_size'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_issuance_class'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_color'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku_cat'))
        batch_op.drop_index(batch_op.f('ix_logi_item_sku'))
        batch_op.drop_index(batch_op.f('ix_logi_item_category'))
        batch_op.drop_index('ix_item_sku_family')

    op.drop_table('logi_item')
    with op.batch_alter_table('ledger_event', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_event_request_id')
        batch_op.drop_index('ix_ledger_event_event_type')
        batch_op.drop_index('ix_ledger_event_chain_key_id')

    op.drop_table('ledger_event')
    with op.batch_alter_table('governance_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_policy_namespace'))
        batch_op.drop_index(batch_op.f('ix_governance_policy_key'))
        batch_op.drop_index(batch_op.f('ix_governance_policy_is_active'))
        batch_op.drop_index('ix_governance_policy_active')

    op.drop_table('governance_policy')
    with op.batch_alter_table('gov_service_class', schema=None) as batch_op:
        batch_op.drop_index('ix_gov_service_class_sort')
        batch_op.drop_index(batch_op.f('ix_gov_service_class_code'))

    op.drop_table('gov_service_class')
    with op.batch_alter_table('gov_role_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gov_role_code_code'))

    op.drop_table('gov_role_code')
    with op.batch_alter_table('gov_canonical_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gov_canonical_state_code'))

    op.drop_table('gov_canonical_state')
    with op.batch_alter_table('finance_stat_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_stat_metric_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_stat_metric_metric_code'))

    op.drop_table('finance_stat_metric')
    with op.batch_alter_table('finance_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_project_active'))

    op.drop_table('finance_project')
    with op.batch_alter_table('finance_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_period_status'))
        batch_op.drop_index(batch_op.f('ix_finance_period_period_key'))

    op.drop_table('finance_period')
    with op.batch_alter_table('finance_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_journal_source'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_journal_external_ref_ulid'))

    op.drop_table('finance_journal')
    with op.batch_alter_table('finance_fund', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_fund_restriction'))
        batch_op.drop_index(batch_op.f('ix_finance_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_fund_active'))

    op.drop_table('finance_fund')
    with op.batch_alter_table('finance_balance_monthly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_period_key'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_monthly_account_code'))

    op.drop_table('finance_balance_monthly')
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_account_type'))
        batch_op.drop_index(batch_op.f('ix_finance_account_code'))
        batch_op.drop_index(batch_op.f('ix_finance_account_active'))

    op.drop_table('finance_account')
    op.drop_table('entity_entity')
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_user_username'))
        batch_op.drop_index(batch_op.f('ix_auth_user_entity_ulid'))
        batch_op.drop_index(batch_op.f('ix_auth_user_email'))

    op.drop_table('auth_user')
    with op.batch_alter_table('auth_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_role_code'))

    op.drop_table('auth_role')
    with op.batch_alter_table('attachment_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_attachment_sha256'))

    op.drop_table('attachment_attachment')
    op.drop_table('admin_cron_status')
    # ### end Alembic commands ###
