"""empty message

Revision ID: 86728e20915d
Revises: 68846e9c95e4
Create Date: 2026-03-23 16:30:32.072713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86728e20915d'
down_revision = '68846e9c95e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_crm_factor_index',
    sa.Column('sponsor_entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('bucket', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('strength', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("source IN ('operator','observed','inferred')", name='ck_sponsor_crm_factor_source'),
    sa.CheckConstraint("strength IN ('observed','recurring','strong_pattern')", name='ck_sponsor_crm_factor_strength'),
    sa.ForeignKeyConstraint(['sponsor_entity_ulid'], ['sponsor_sponsor.entity_ulid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('sponsor_entity_ulid', 'bucket', 'key', name='uq_sponsor_crm_factor_triplet')
    )
    with op.batch_alter_table('sponsor_crm_factor_index', schema=None) as batch_op:
        batch_op.create_index('ix_sponsor_crm_factor_bucket_key_active', ['bucket', 'key', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_crm_factor_index_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_crm_factor_index_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_crm_factor_index_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_crm_factor_index_sponsor_entity_ulid'), ['sponsor_entity_ulid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_crm_factor_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_crm_factor_index_sponsor_entity_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_crm_factor_index_key'))
        batch_op.drop_index(batch_op.f('ix_sponsor_crm_factor_index_bucket'))
        batch_op.drop_index(batch_op.f('ix_sponsor_crm_factor_index_active'))
        batch_op.drop_index('ix_sponsor_crm_factor_bucket_key_active')

    op.drop_table('sponsor_crm_factor_index')
    # ### end Alembic commands ###
