"""empty message

Revision ID: 93aecaaa8f00
Revises: 488a7f31d9a8
Create Date: 2026-04-22 20:04:08.994097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aecaaa8f00'
down_revision = '488a7f31d9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_admin_issue',
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('resource_admin_issue', schema=None) as batch_op:
        batch_op.create_index('ix_resource_admin_issue_active', ['reason_code', 'source_status', 'closed_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_admin_issue_closed_at_utc'), ['closed_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_admin_issue_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_admin_issue_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_resource_admin_issue_request_reason', ['request_id', 'reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_admin_issue_source_status'), ['source_status'], unique=False)
        batch_op.create_index('ix_resource_admin_issue_target_reason', ['target_ulid', 'reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_admin_issue_target_ulid'), ['target_ulid'], unique=False)

    with op.batch_alter_table('resource_admin_review_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_admin_review_request_active'))

    op.drop_table('resource_admin_review_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_admin_review_request',
    sa.Column('entity_ulid', sa.VARCHAR(length=26), nullable=False),
    sa.Column('review_kind', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('requested_by_actor_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.VARCHAR(length=26), nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('closed_at_utc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ulid', sa.VARCHAR(length=26), nullable=False),
    sa.Column('created_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('resource_admin_review_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_admin_review_request_active'), ['entity_ulid', 'review_kind', 'source_status'], unique=False)

    with op.batch_alter_table('resource_admin_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_admin_issue_target_ulid'))
        batch_op.drop_index('ix_resource_admin_issue_target_reason')
        batch_op.drop_index(batch_op.f('ix_resource_admin_issue_source_status'))
        batch_op.drop_index('ix_resource_admin_issue_request_reason')
        batch_op.drop_index(batch_op.f('ix_resource_admin_issue_request_id'))
        batch_op.drop_index(batch_op.f('ix_resource_admin_issue_reason_code'))
        batch_op.drop_index(batch_op.f('ix_resource_admin_issue_closed_at_utc'))
        batch_op.drop_index('ix_resource_admin_issue_active')

    op.drop_table('resource_admin_issue')
    # ### end Alembic commands ###
