"""add finance sweep run and issue oper note

Revision ID: 98db0dea8b28
Revises: 4f31e74dce7b
Create Date: 2026-04-28 19:32:01.421115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98db0dea8b28'
down_revision = '4f31e74dce7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_sweep_run',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('ran_at_utc', sa.String(length=30), nullable=False),
    sa.Column('scans_run', sa.Integer(), nullable=False),
    sa.Column('clean_count', sa.Integer(), nullable=False),
    sa.Column('dirty_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('quarantine_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('clean_count >= 0 and dirty_count >= 0 and issue_count >= 0 and quarantine_count >= 0', name='ck_finance_sweep_run_counts_nonnegative'),
    sa.CheckConstraint('scans_run >= 0', name='ck_finance_sweep_run_scans_nonnegative'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_sweep_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_sweep_run_actor_ulid'), ['actor_ulid'], unique=False)
        batch_op.create_index('ix_finance_sweep_run_ran_actor', ['ran_at_utc', 'actor_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_sweep_run_ran_at_utc'), ['ran_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_sweep_run_request_id'), ['request_id'], unique=True)

    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oper_note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_admin_issue', schema=None) as batch_op:
        batch_op.drop_column('oper_note')

    with op.batch_alter_table('finance_sweep_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_sweep_run_request_id'))
        batch_op.drop_index(batch_op.f('ix_finance_sweep_run_ran_at_utc'))
        batch_op.drop_index('ix_finance_sweep_run_ran_actor')
        batch_op.drop_index(batch_op.f('ix_finance_sweep_run_actor_ulid'))

    op.drop_table('finance_sweep_run')
    # ### end Alembic commands ###
