"""add finance_posting_fact

Revision ID: aa0ecdd4cb1c
Revises: 05522b3f9662
Create Date: 2026-04-13 21:01:50.324040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0ecdd4cb1c'
down_revision = '05522b3f9662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_posting_fact',
    sa.Column('journal_ulid', sa.String(length=26), nullable=False),
    sa.Column('request_id', sa.String(length=26), nullable=False),
    sa.Column('posting_family', sa.String(length=16), nullable=False),
    sa.Column('semantic_key', sa.String(length=64), nullable=False),
    sa.Column('method_key', sa.String(length=32), nullable=False),
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('project_ulid', sa.String(length=26), nullable=True),
    sa.Column('fund_code', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('happened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("posting_family in ('income','expense')", name='ck_postfact_family'),
    sa.CheckConstraint('amount_cents >= 0', name='ck_postfact_nonneg'),
    sa.ForeignKeyConstraint(['journal_ulid'], ['finance_journal.ulid'], ),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('journal_ulid', name='uq_postfact_journal')
    )
    with op.batch_alter_table('finance_posting_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_actor_ulid'), ['actor_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_happened_at_utc'), ['happened_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_journal_ulid'), ['journal_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_method_key'), ['method_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_posting_family'), ['posting_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_semantic_key'), ['semantic_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_source_ref_ulid'), ['source_ref_ulid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_posting_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_source_ref_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_source'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_semantic_key'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_request_id'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_project_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_posting_family'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_method_key'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_journal_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_happened_at_utc'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_funding_demand_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_fund_code'))
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_actor_ulid'))

    op.drop_table('finance_posting_fact')
    # ### end Alembic commands ###
