"""empty message

Revision ID: bc364c7e43e1
Revises: aa0ecdd4cb1c
Create Date: 2026-04-19 20:53:11.895170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc364c7e43e1'
down_revision = 'aa0ecdd4cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intake_step', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('intake_request_id', sa.String(length=26), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_entity', schema=None) as batch_op:
        batch_op.drop_column('intake_request_id')
        batch_op.drop_column('intake_step')

    # ### end Alembic commands ###
