"""empty message

Revision ID: c7b83a72a354
Revises: 1bc4b0e02e6c
Create Date: 2026-04-25 21:13:44.716266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b83a72a354'
down_revision = '1bc4b0e02e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_admin_issue',
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('target_ulid', sa.String(length=26), nullable=True),
    sa.Column('chain_key', sa.String(length=40), nullable=True),
    sa.Column('event_ulid', sa.String(length=26), nullable=True),
    sa.Column('requested_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('resolved_by_actor_ulid', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('ledger_admin_issue', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_admin_issue_chain', ['chain_key', 'reason_code'], unique=False)
        batch_op.create_index('ix_ledger_admin_issue_open', ['source_status', 'updated_at_utc'], unique=False)
        batch_op.create_index('ix_ledger_admin_issue_request_reason', ['request_id', 'reason_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_admin_issue', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_admin_issue_request_reason')
        batch_op.drop_index('ix_ledger_admin_issue_open')
        batch_op.drop_index('ix_ledger_admin_issue_chain')

    op.drop_table('ledger_admin_issue')
    # ### end Alembic commands ###
