"""empty message

Revision ID: c7ebc17fd515
Revises: e0afab29f292
Create Date: 2025-12-12 08:13:19.022575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ebc17fd515'
down_revision = 'e0afab29f292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_grant',
    sa.Column('fund_id', sa.String(length=26), nullable=False),
    sa.Column('sponsor_ulid', sa.String(length=26), nullable=False),
    sa.Column('amount_awarded_cents', sa.Integer(), nullable=False),
    sa.Column('match_required_cents', sa.Integer(), nullable=False),
    sa.Column('start_on', sa.String(length=10), nullable=False),
    sa.Column('end_on', sa.String(length=10), nullable=False),
    sa.Column('reporting_frequency', sa.String(length=16), nullable=False),
    sa.Column('allowable_categories_raw', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("reporting_frequency in ('monthly','quarterly','semiannual','annual','end_of_term')", name='ck_grant_reporting_frequency'),
    sa.ForeignKeyConstraint(['fund_id'], ['finance_fund.ulid'], ),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_grant_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_reporting_frequency'), ['reporting_frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_grant_sponsor_ulid'), ['sponsor_ulid'], unique=False)

    op.create_table('finance_reimbursement',
    sa.Column('grant_id', sa.String(length=26), nullable=False),
    sa.Column('submitted_on', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('draft','submitted','approved','paid','void')", name='ck_reimbursement_status'),
    sa.ForeignKeyConstraint(['grant_id'], ['finance_grant.ulid'], ),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('finance_reimbursement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_reimbursement_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_reimbursement_status'), ['status'], unique=False)

    op.create_table('funding_plan',
    sa.Column('project_ulid', sa.String(length=26), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=True),
    sa.Column('fund_archetype_key', sa.String(length=32), nullable=True),
    sa.Column('expected_amount_cents', sa.Integer(), nullable=True),
    sa.Column('is_in_kind', sa.Boolean(), nullable=False),
    sa.Column('expected_sponsor_hint', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint('expected_amount_cents IS NULL OR expected_amount_cents >= 0', name='ck_funding_plan_expected_nonneg'),
    sa.ForeignKeyConstraint(['project_ulid'], ['project_project.ulid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('funding_plan', schema=None) as batch_op:
        batch_op.create_index('ix_funding_plan_archetype', ['fund_archetype_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_plan_fund_archetype_key'), ['fund_archetype_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_plan_is_in_kind'), ['is_in_kind'], unique=False)
        batch_op.create_index('ix_funding_plan_project', ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_plan_project_ulid'), ['project_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_plan_source_kind'), ['source_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_plan_source_kind'))
        batch_op.drop_index(batch_op.f('ix_funding_plan_project_ulid'))
        batch_op.drop_index('ix_funding_plan_project')
        batch_op.drop_index(batch_op.f('ix_funding_plan_is_in_kind'))
        batch_op.drop_index(batch_op.f('ix_funding_plan_fund_archetype_key'))
        batch_op.drop_index('ix_funding_plan_archetype')

    op.drop_table('funding_plan')
    with op.batch_alter_table('finance_reimbursement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_reimbursement_status'))
        batch_op.drop_index(batch_op.f('ix_finance_reimbursement_grant_id'))

    op.drop_table('finance_reimbursement')
    with op.batch_alter_table('finance_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_grant_sponsor_ulid'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_reporting_frequency'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_fund_id'))
        batch_op.drop_index(batch_op.f('ix_finance_grant_active'))

    op.drop_table('finance_grant')
    # ### end Alembic commands ###
