"""empty message

Revision ID: cf19ba0b998c
Revises: 52b4b6a702b5
Create Date: 2026-03-28 08:49:46.679202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf19ba0b998c'
down_revision = '52b4b6a702b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_inbox_archive',
    sa.Column('original_inbox_ulid', sa.String(length=26), nullable=False),
    sa.Column('source_slice', sa.String(length=64), nullable=False),
    sa.Column('issue_kind', sa.String(length=128), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=False),
    sa.Column('subject_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('admin_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=False),
    sa.Column('resolution_route', sa.String(length=200), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('archived_at_utc', sa.String(length=30), nullable=False),
    sa.Column('archive_reason', sa.String(length=64), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('original_inbox_ulid')
    )
    with op.batch_alter_table('admin_inbox_archive', schema=None) as batch_op:
        batch_op.create_index('ix_admin_inbox_archive_archived_at', ['archived_at_utc'], unique=False)
        batch_op.create_index('ix_admin_inbox_archive_source', ['source_slice', 'issue_kind'], unique=False)
        batch_op.create_index('ix_admin_inbox_source_ref_ulid', ['source_ref_ulid'], unique=False)

    op.create_table('admin_inbox_item',
    sa.Column('source_slice', sa.String(length=64), nullable=False),
    sa.Column('issue_kind', sa.String(length=128), nullable=False),
    sa.Column('source_ref_ulid', sa.String(length=26), nullable=False),
    sa.Column('subject_ref_ulid', sa.String(length=26), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=64), nullable=False),
    sa.Column('admin_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_key', sa.String(length=128), nullable=False),
    sa.Column('resolution_route', sa.String(length=200), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('opened_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_by_ulid', sa.String(length=26), nullable=True),
    sa.Column('acknowledged_at_utc', sa.String(length=30), nullable=True),
    sa.Column('closed_at_utc', sa.String(length=30), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('ulid'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('admin_inbox_item', schema=None) as batch_op:
        batch_op.create_index('ix_admin_inbox_item_active', ['admin_status', 'severity', 'updated_at_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_inbox_item', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_inbox_item_active')

    op.drop_table('admin_inbox_item')
    with op.batch_alter_table('admin_inbox_archive', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_inbox_source_ref_ulid')
        batch_op.drop_index('ix_admin_inbox_archive_source')
        batch_op.drop_index('ix_admin_inbox_archive_archived_at')

    op.drop_table('admin_inbox_archive')
    # ### end Alembic commands ###
