"""empty message

Revision ID: d0fd65c6bd1f
Revises: eb2921a86a4e
Create Date: 2026-03-12 09:16:21.277224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fd65c6bd1f'
down_revision = 'eb2921a86a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_funding_intent',
    sa.Column('sponsor_entity_ulid', sa.String(length=26), nullable=False),
    sa.Column('funding_demand_ulid', sa.String(length=26), nullable=False),
    sa.Column('intent_kind', sa.String(length=24), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('created_at_utc', sa.String(length=30), nullable=False),
    sa.Column('updated_at_utc', sa.String(length=30), nullable=False),
    sa.CheckConstraint("intent_kind IN ('pledge','donation','pass_through')", name='ck_sfi_intent_kind'),
    sa.CheckConstraint("status IN ('draft','committed','withdrawn','fulfilled')", name='ck_sfi_status'),
    sa.CheckConstraint('amount_cents >= 0', name='ck_sfi_amount_nonneg'),
    sa.ForeignKeyConstraint(['sponsor_entity_ulid'], ['sponsor_sponsor.entity_ulid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ulid')
    )
    with op.batch_alter_table('sponsor_funding_intent', schema=None) as batch_op:
        batch_op.create_index('ix_sfi_demand_status', ['funding_demand_ulid', 'status'], unique=False)
        batch_op.create_index('ix_sfi_sponsor_demand', ['sponsor_entity_ulid', 'funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_funding_intent_funding_demand_ulid'), ['funding_demand_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_funding_intent_intent_kind'), ['intent_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_funding_intent_sponsor_entity_ulid'), ['sponsor_entity_ulid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_funding_intent_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_funding_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_funding_intent_status'))
        batch_op.drop_index(batch_op.f('ix_sponsor_funding_intent_sponsor_entity_ulid'))
        batch_op.drop_index(batch_op.f('ix_sponsor_funding_intent_intent_kind'))
        batch_op.drop_index(batch_op.f('ix_sponsor_funding_intent_funding_demand_ulid'))
        batch_op.drop_index('ix_sfi_sponsor_demand')
        batch_op.drop_index('ix_sfi_demand_status')

    op.drop_table('sponsor_funding_intent')
    # ### end Alembic commands ###
