"""empty message

Revision ID: db8d7df1ee81
Revises: 0ebeaf31225e
Create Date: 2026-04-27 08:42:25.997165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8d7df1ee81'
down_revision = '0ebeaf31225e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_posting_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=200), nullable=False))
        batch_op.create_index(batch_op.f('ix_finance_posting_fact_idempotency_key'), ['idempotency_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_posting_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_posting_fact_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
