"""logistics: add decision_json to logi_issue

Revision ID: df2fb7b7b026
Revises: 75d50de110e0
Create Date: 2025-10-31 07:30:51.198058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2fb7b7b026'
down_revision = '75d50de110e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logi_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logi_issue', schema=None) as batch_op:
        batch_op.drop_column('decision_json')

    # ### end Alembic commands ###
