"""empty message

Revision ID: e0afab29f292
Revises: e5cef456d362
Create Date: 2025-12-03 06:18:19.631323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0afab29f292"
down_revision = "e5cef456d362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsor_funding_prospect",
        sa.Column("sponsor_ulid", sa.String(length=26), nullable=False),
        sa.Column("project_type_key", sa.String(length=32), nullable=False),
        sa.Column("fund_archetype_key", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("est_min_cents", sa.Integer(), nullable=True),
        sa.Column("est_max_cents", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("realized_total_cents", sa.Integer(), nullable=False),
        sa.Column("ulid", sa.String(length=26), nullable=False),
        sa.Column("created_at_utc", sa.String(length=30), nullable=False),
        sa.Column("updated_at_utc", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name="ck_funding_prospect_confidence_range",
        ),
        sa.CheckConstraint(
            "est_max_cents IS NULL OR est_max_cents >= 0",
            name="ck_funding_prospect_max_nonneg",
        ),
        sa.CheckConstraint(
            "est_min_cents IS NULL OR est_max_cents IS NULL OR est_min_cents <= est_max_cents",
            name="ck_funding_prospect_min_le_max",
        ),
        sa.CheckConstraint(
            "est_min_cents IS NULL OR est_min_cents >= 0",
            name="ck_funding_prospect_min_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_ulid"], ["sponsor_sponsor.ulid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("ulid"),
    )
    with op.batch_alter_table(
        "sponsor_funding_prospect", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sponsor_funding_prospect_fund_archetype_key"),
            ["fund_archetype_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sponsor_funding_prospect_project_type_key"),
            ["project_type_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sponsor_funding_prospect_sponsor_ulid"),
            ["sponsor_ulid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sponsor_funding_prospect_status"),
            ["status"],
            unique=False,
        )

    with op.batch_alter_table("sponsor_allocation", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_sponsor_allocation_approved_by_ulid")
        )
        batch_op.drop_index(batch_op.f("ix_sponsor_allocation_customer_ulid"))
        batch_op.drop_index(batch_op.f("ix_sponsor_allocation_sponsor_ulid"))
        batch_op.drop_index(batch_op.f("ix_sponsor_allocation_state"))

    op.drop_table("sponsor_allocation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
