"""empty message

Revision ID: e12b9947225e
Revises: 5426b725de2d
Create Date: 2026-04-06 23:47:34.160273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e12b9947225e'
down_revision = '5426b725de2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligible_fund_codes_json', sa.JSON(), nullable=True))
        batch_op.drop_column('eligible_fund_keys_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligible_fund_keys_json', sqlite.JSON(), nullable=True))
        batch_op.drop_column('eligible_fund_codes_json')

    # ### end Alembic commands ###
