"""empty message

Revision ID: eb2921a86a4e
Revises: 4d1977045f3a
Create Date: 2026-03-11 20:58:54.677924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2921a86a4e'
down_revision = '4d1977045f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ulid', sa.String(length=26), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('ulid')

    # ### end Alembic commands ###
