"""resource_overhaul

Revision ID: ee831be61a9c
Revises: ce437fd10a7f
Create Date: 2025-09-27 06:58:55.232062

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee831be61a9c"
down_revision = "ce437fd10a7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources_location",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address1", sa.String(length=200), nullable=True),
        sa.Column("address2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("postal", sa.String(length=20), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at_utc",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources_resource",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attributes_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at_utc",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resources_resource", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resources_resource_code"), ["code"], unique=True
        )

    op.create_table(
        "resources_assignment",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("resource_id", sa.String(length=26), nullable=False),
        sa.Column("window_start_utc", sa.DateTime(), nullable=False),
        sa.Column("window_end_utc", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ref_event_id", sa.String(length=26), nullable=True),
        sa.Column("ref_issuance_id", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at_utc",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources_resource.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "resources_assignment", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resources_assignment_ref_event_id"),
            ["ref_event_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resources_assignment_ref_issuance_id"),
            ["ref_issuance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resources_assignment_resource_id"),
            ["resource_id"],
            unique=False,
        )

    with op.batch_alter_table("entity_org", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ux_entity_org_ein_notnull"),
            sqlite_where=sa.text("ein IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_org", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ux_entity_org_ein_notnull"),
            ["ein"],
            unique=1,
            sqlite_where=sa.text("ein IS NOT NULL"),
        )

    with op.batch_alter_table(
        "resources_assignment", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resources_assignment_resource_id"))
        batch_op.drop_index(
            batch_op.f("ix_resources_assignment_ref_issuance_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_resources_assignment_ref_event_id")
        )

    op.drop_table("resources_assignment")
    with op.batch_alter_table("resources_resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resources_resource_code"))

    op.drop_table("resources_resource")
    op.drop_table("resources_location")
    # ### end Alembic commands ###
